// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module image_filter_Dilate_0_0_1080_1920_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st12_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv11_5 = 11'b101;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_7FD = 11'b11111111101;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_4 = 11'b100;
parameter    ap_const_lv12_FFC = 12'b111111111100;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv12_FFB = 12'b111111111011;
parameter    ap_const_lv12_FFA = 12'b111111111010;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_24;
reg   [10:0] p_025_0_i_i_reg_263;
reg    ap_sig_bdd_48;
wire   [10:0] heightloop_fu_324_p2;
reg   [10:0] heightloop_reg_1240;
wire   [10:0] widthloop_fu_330_p2;
reg   [10:0] widthloop_reg_1245;
wire   [11:0] tmp_14_cast_fu_342_p1;
reg   [11:0] tmp_14_cast_reg_1250;
wire   [1:0] p_neg226_i_i_cast_fu_350_p2;
reg   [1:0] p_neg226_i_i_cast_reg_1255;
wire   [10:0] ref_fu_356_p2;
reg   [10:0] ref_reg_1261;
wire   [11:0] ref_cast_fu_362_p1;
reg   [11:0] ref_cast_reg_1267;
wire   [10:0] tmp_2_i_fu_366_p2;
reg   [10:0] tmp_2_i_reg_1272;
wire   [1:0] tmp_2_i1_fu_376_p2;
reg   [1:0] tmp_2_i1_reg_1277;
wire   [10:0] i_V_fu_391_p2;
reg   [10:0] i_V_reg_1286;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_76;
wire   [0:0] tmp_17_fu_397_p2;
reg   [0:0] tmp_17_reg_1291;
wire   [0:0] tmp_16_fu_386_p2;
wire   [0:0] tmp_23_fu_409_p2;
reg   [0:0] tmp_23_reg_1296;
wire   [0:0] or_cond_fu_436_p2;
reg   [0:0] or_cond_reg_1301;
reg   [0:0] tmp_107_reg_1306;
wire   [1:0] tmp_108_fu_457_p1;
reg   [1:0] tmp_108_reg_1310;
wire   [1:0] tmp_111_fu_473_p3;
reg   [1:0] tmp_111_reg_1316;
wire   [0:0] or_cond_i1_fu_506_p2;
reg   [0:0] or_cond_i1_reg_1322;
reg   [0:0] tmp_113_reg_1327;
wire   [1:0] tmp_114_fu_520_p1;
reg   [1:0] tmp_114_reg_1332;
wire   [1:0] tmp_115_fu_524_p1;
reg   [1:0] tmp_115_reg_1337;
wire   [0:0] or_cond_i2_fu_553_p2;
reg   [0:0] or_cond_i2_reg_1344;
reg   [0:0] tmp_117_reg_1349;
wire   [1:0] tmp_118_fu_567_p1;
reg   [1:0] tmp_118_reg_1354;
wire   [0:0] sel_tmp8_fu_575_p2;
reg   [0:0] sel_tmp8_reg_1359;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_116;
wire   [0:0] sel_tmp3_fu_579_p2;
reg   [0:0] sel_tmp3_reg_1364;
wire   [0:0] sel_tmp4_fu_602_p2;
reg   [0:0] sel_tmp4_reg_1369;
wire   [0:0] sel_tmp7_fu_607_p2;
reg   [0:0] sel_tmp7_reg_1374;
wire   [1:0] locy_2_t_fu_625_p2;
reg   [1:0] locy_2_t_reg_1379;
wire   [0:0] brmerge_fu_630_p2;
reg   [0:0] brmerge_reg_1383;
wire   [0:0] tmp_19_fu_638_p2;
reg   [0:0] tmp_19_reg_1387;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_bdd_135;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_19_reg_1387_pp0_it1;
reg   [0:0] or_cond2_reg_1419;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1419_pp0_it1;
reg    ap_sig_bdd_154;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] or_cond219_i_i_reg_1396;
reg   [0:0] ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6;
reg    ap_sig_bdd_172;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_19_reg_1387_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_19_reg_1387_pp0_it3;
reg   [0:0] ap_reg_ppstg_tmp_19_reg_1387_pp0_it4;
wire   [10:0] j_V_fu_643_p2;
wire   [0:0] or_cond219_i_i_fu_665_p2;
reg   [0:0] ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5;
wire   [10:0] tmp_120_fu_676_p1;
reg   [10:0] tmp_120_reg_1400;
wire   [0:0] tmp_i_fu_698_p2;
reg   [0:0] tmp_i_reg_1405;
reg   [0:0] ap_reg_ppstg_tmp_i_reg_1405_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_i_reg_1405_pp0_it2;
wire   [0:0] or_cond_i_fu_703_p2;
reg   [0:0] or_cond_i_reg_1409;
reg   [0:0] tmp_123_reg_1414;
reg   [0:0] ap_reg_ppstg_tmp_123_reg_1414_pp0_it1;
reg   [0:0] ap_reg_ppstg_tmp_123_reg_1414_pp0_it2;
wire   [0:0] or_cond2_fu_723_p2;
reg   [0:0] ap_reg_ppstg_or_cond2_reg_1419_pp0_it2;
wire   [0:0] tmp_29_fu_729_p2;
reg   [0:0] tmp_29_reg_1423;
reg   [0:0] ap_reg_ppstg_tmp_29_reg_1423_pp0_it1;
wire   [1:0] col_assign_fu_734_p2;
reg   [1:0] col_assign_reg_1427;
reg   [1:0] ap_reg_ppstg_col_assign_reg_1427_pp0_it1;
reg   [10:0] k_buf_0_val_0_addr_reg_1433;
reg   [10:0] k_buf_0_val_1_addr_reg_1439;
reg   [10:0] k_buf_0_val_2_addr_reg_1445;
wire   [1:0] col_assign_1_fu_762_p2;
reg   [1:0] col_assign_1_reg_1451;
reg   [1:0] ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2;
wire   [7:0] k_buf_0_val_0_q0;
reg   [7:0] right_border_buf_0_val_2_0_reg_1457;
wire   [7:0] k_buf_0_val_1_q0;
reg   [7:0] right_border_buf_0_val_1_0_reg_1464;
wire   [7:0] k_buf_0_val_2_q0;
reg   [7:0] src_kernel_win_0_val_2_0_reg_1471;
wire   [7:0] temp_0_i_i_i_057_i_i_1_0_1_fu_910_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_0_1_reg_1477;
reg   [7:0] src_kernel_win_0_val_0_1_6_reg_1483;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5;
reg   [7:0] src_kernel_win_0_val_1_1_6_reg_1490;
reg   [7:0] src_kernel_win_0_val_1_2_lo_reg_1496;
wire   [7:0] temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_0_2_reg_1501;
wire   [0:0] tmp_139_1_fu_1033_p2;
reg   [0:0] tmp_139_1_reg_1506;
reg   [7:0] src_kernel_win_0_val_0_1_lo_reg_1511;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it5;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6;
reg   [7:0] src_kernel_win_0_val_1_1_lo_reg_1517;
wire   [7:0] temp_0_i_i_i_057_i_i_1_1_1_fu_1060_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_1_1_reg_1523;
reg   [7:0] src_kernel_win_0_val_0_2_lo_reg_1529;
wire   [7:0] temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_1_2_reg_1534;
wire   [0:0] tmp_139_2_fu_1080_p2;
reg   [0:0] tmp_139_2_reg_1539;
wire   [7:0] temp_0_i_i_i_057_i_i_1_2_1_fu_1100_p3;
reg   [7:0] temp_0_i_i_i_057_i_i_1_2_1_reg_1544;
wire   [10:0] k_buf_0_val_0_address0;
reg    k_buf_0_val_0_ce0;
wire   [10:0] k_buf_0_val_0_address1;
reg    k_buf_0_val_0_ce1;
reg    k_buf_0_val_0_we1;
wire   [7:0] k_buf_0_val_0_d1;
wire   [10:0] k_buf_0_val_1_address0;
reg    k_buf_0_val_1_ce0;
wire   [10:0] k_buf_0_val_1_address1;
reg    k_buf_0_val_1_ce1;
reg    k_buf_0_val_1_we1;
wire   [7:0] k_buf_0_val_1_d1;
wire   [10:0] k_buf_0_val_2_address0;
reg    k_buf_0_val_2_ce0;
wire   [10:0] k_buf_0_val_2_address1;
reg    k_buf_0_val_2_ce1;
reg    k_buf_0_val_2_we1;
wire   [7:0] k_buf_0_val_2_d1;
reg   [10:0] p_012_0_i_i_reg_252;
reg    ap_sig_cseq_ST_st12_fsm_4;
reg    ap_sig_bdd_355;
wire   [63:0] tmp_80_fu_755_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_106;
wire   [7:0] src_kernel_win_0_val_0_0_fu_934_p3;
wire   [7:0] col_buf_0_val_0_0_9_fu_989_p3;
reg   [7:0] src_kernel_win_0_val_0_2_fu_110;
reg   [7:0] col_buf_0_val_0_0_3_fu_114;
reg   [7:0] src_kernel_win_0_val_2_1_fu_118;
reg   [7:0] src_kernel_win_0_val_1_1_fu_122;
wire   [7:0] src_kernel_win_0_val_1_0_fu_946_p3;
wire   [7:0] right_border_buf_0_val_1_2_11_fu_1006_p3;
reg   [7:0] src_kernel_win_0_val_1_2_fu_126;
reg   [7:0] col_buf_0_val_0_0_5_fu_130;
reg   [7:0] src_kernel_win_0_val_2_2_fu_134;
reg   [7:0] col_buf_0_val_0_0_6_fu_138;
reg   [7:0] right_border_buf_0_val_1_2_1_fu_142;
wire   [7:0] right_border_buf_0_val_1_2_8_fu_877_p3;
reg   [7:0] right_border_buf_0_val_1_2_2_fu_146;
wire   [7:0] right_border_buf_0_val_1_2_6_fu_868_p3;
reg   [7:0] right_border_buf_0_val_1_2_7_fu_150;
wire   [7:0] right_border_buf_0_val_1_2_4_fu_851_p3;
reg   [7:0] right_border_buf_0_val_0_0_fu_166;
reg   [7:0] right_border_buf_0_val_0_1_fu_170;
reg   [7:0] right_border_buf_0_val_0_2_fu_174;
wire   [10:0] tmp_fu_316_p1;
wire   [10:0] tmp_103_fu_320_p1;
wire   [10:0] tmp_14_fu_336_p2;
wire   [1:0] tmp_104_fu_346_p1;
wire   [1:0] tmp_105_fu_372_p1;
wire   [11:0] tmp_15_cast_cast_fu_382_p1;
wire   [11:0] ImagLoc_y_fu_403_p2;
wire   [10:0] tmp_106_fu_415_p4;
wire   [0:0] icmp_fu_425_p2;
wire   [0:0] tmp_25_fu_431_p2;
wire   [10:0] p_i_i_fu_450_p3;
wire   [0:0] tmp_i5_fu_461_p2;
wire   [1:0] tmp_109_fu_466_p1;
wire   [1:0] tmp_110_fu_470_p1;
wire   [11:0] y_1_fu_481_p2;
wire   [0:0] tmp_112_fu_487_p3;
wire   [0:0] tmp_i1_fu_501_p2;
wire   [0:0] rev_fu_495_p2;
wire   [11:0] y_1_1_fu_528_p2;
wire   [0:0] tmp_116_fu_534_p3;
wire   [0:0] tmp_i2_fu_548_p2;
wire   [0:0] rev1_fu_542_p2;
wire   [1:0] locy_fu_571_p2;
wire   [1:0] tmp_s_fu_585_p3;
wire   [1:0] tmp_81_fu_591_p3;
wire   [1:0] locy_1_t_fu_597_p2;
wire   [1:0] tmp_82_fu_613_p3;
wire   [1:0] tmp_83_fu_619_p3;
wire   [9:0] tmp_119_fu_649_p4;
wire   [0:0] icmp2_fu_659_p2;
wire   [11:0] tmp_18_cast_fu_634_p1;
wire   [11:0] ImagLoc_x_fu_670_p2;
wire   [0:0] tmp_122_fu_684_p3;
wire   [0:0] rev2_fu_692_p2;
wire   [0:0] tmp_26_fu_717_p2;
wire   [1:0] tmp_121_fu_680_p1;
wire   [10:0] p_assign_fu_739_p3;
wire   [10:0] p_assign_1_i_fu_745_p3;
wire   [1:0] tmp_124_fu_751_p1;
wire   [0:0] sel_tmp1_fu_833_p2;
wire   [0:0] sel_tmp5_fu_846_p2;
wire   [7:0] right_border_buf_0_val_1_2_3_fu_838_p3;
wire   [7:0] right_border_buf_0_val_1_2_5_fu_860_p3;
wire   [0:0] tmp_139_0_1_fu_904_p2;
wire   [7:0] sel_tmp9_fu_929_p3;
wire   [7:0] sel_tmp6_fu_941_p3;
wire   [0:0] sel_tmp_fu_971_p2;
wire   [0:0] sel_tmp2_fu_984_p2;
wire   [7:0] col_buf_0_val_0_0_2_fu_976_p3;
wire   [7:0] right_border_buf_0_val_1_2_fu_998_p3;
wire   [0:0] tmp_139_0_2_fu_1021_p2;
wire   [7:0] temp_0_i_i_i_057_i_i_1_1_fu_1050_p3;
wire   [0:0] tmp_139_1_1_fu_1055_p2;
wire   [0:0] tmp_139_1_2_fu_1070_p2;
wire   [7:0] temp_0_i_i_i_057_i_i_1_2_fu_1090_p3;
wire   [0:0] tmp_139_2_1_fu_1095_p2;
wire   [0:0] tmp_139_2_2_fu_1107_p2;
reg   [4:0] ap_NS_fsm;


image_filter_FAST_t_opr_k_buf_val_0_V #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_0_address0 ),
    .ce0( k_buf_0_val_0_ce0 ),
    .q0( k_buf_0_val_0_q0 ),
    .address1( k_buf_0_val_0_address1 ),
    .ce1( k_buf_0_val_0_ce1 ),
    .we1( k_buf_0_val_0_we1 ),
    .d1( k_buf_0_val_0_d1 )
);

image_filter_FAST_t_opr_k_buf_val_0_V #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_1_address0 ),
    .ce0( k_buf_0_val_1_ce0 ),
    .q0( k_buf_0_val_1_q0 ),
    .address1( k_buf_0_val_1_address1 ),
    .ce1( k_buf_0_val_1_ce1 ),
    .we1( k_buf_0_val_1_we1 ),
    .d1( k_buf_0_val_1_d1 )
);

image_filter_FAST_t_opr_k_buf_val_0_V #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_2_address0 ),
    .ce0( k_buf_0_val_2_ce0 ),
    .q0( k_buf_0_val_2_q0 ),
    .address1( k_buf_0_val_2_address1 ),
    .ce1( k_buf_0_val_2_ce1 ),
    .we1( k_buf_0_val_2_we1 ),
    .d1( k_buf_0_val_2_d1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_done_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_16_fu_386_p2 == ap_const_lv1_0))) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_19_fu_638_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) begin
                ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_4)) begin
        p_012_0_i_i_reg_252 <= i_V_reg_1286;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_48)) begin
        p_012_0_i_i_reg_252 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_fu_638_p2))) begin
        p_025_0_i_i_reg_263 <= j_V_fu_643_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_025_0_i_i_reg_263 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2)) | (~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2)))) begin
        src_kernel_win_0_val_0_1_fu_106 <= right_border_buf_0_val_2_0_reg_1457;
    end else if (((~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) & (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) & (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) & ~(ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_106 <= col_buf_0_val_0_0_9_fu_989_p3;
    end else if ((((ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == tmp_107_reg_1306) & (locy_2_t_reg_1379 == ap_const_lv2_1)) | ((ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == tmp_107_reg_1306) & (locy_2_t_reg_1379 == ap_const_lv2_0)) | ((ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == tmp_107_reg_1306) & ~(locy_2_t_reg_1379 == ap_const_lv2_1) & ~(locy_2_t_reg_1379 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_106 <= src_kernel_win_0_val_0_0_fu_934_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2)) | (~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2)))) begin
        src_kernel_win_0_val_1_1_fu_122 <= right_border_buf_0_val_1_0_reg_1464;
    end else if (((~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) & (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) & (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) & ~(ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_122 <= right_border_buf_0_val_1_2_11_fu_1006_p3;
    end else if ((((ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == tmp_107_reg_1306) & (locy_2_t_reg_1379 == ap_const_lv2_1)) | ((ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == tmp_107_reg_1306) & (locy_2_t_reg_1379 == ap_const_lv2_0)) | ((ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & (ap_const_lv1_0 == tmp_107_reg_1306) & ~(locy_2_t_reg_1379 == ap_const_lv2_1) & ~(locy_2_t_reg_1379 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_122 <= src_kernel_win_0_val_1_0_fu_946_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it1) & ~(col_assign_1_reg_1451 == ap_const_lv2_1) & ~(col_assign_1_reg_1451 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_118 <= right_border_buf_0_val_0_2_fu_174;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it1) & (col_assign_1_reg_1451 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_118 <= right_border_buf_0_val_0_0_fu_166;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_i_reg_1405_pp0_it1) & (col_assign_1_reg_1451 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_118 <= right_border_buf_0_val_0_1_fu_170;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_107_reg_1306) & ~(locy_2_t_reg_1379 == ap_const_lv2_1) & ~(locy_2_t_reg_1379 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_123_reg_1414_pp0_it1)))) begin
        src_kernel_win_0_val_2_1_fu_118 <= k_buf_0_val_2_q0;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_107_reg_1306) & (locy_2_t_reg_1379 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_118 <= k_buf_0_val_0_q0;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1383) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_107_reg_1306) & (locy_2_t_reg_1379 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_118 <= k_buf_0_val_1_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
        ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 <= col_assign_1_reg_1451;
        ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1;
        ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2;
        ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3;
        ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4;
        ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5;
        ap_reg_ppstg_or_cond2_reg_1419_pp0_it2 <= ap_reg_ppstg_or_cond2_reg_1419_pp0_it1;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4 <= src_kernel_win_0_val_0_1_6_reg_1483;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it5 <= src_kernel_win_0_val_0_1_lo_reg_1511;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it5;
        ap_reg_ppstg_tmp_123_reg_1414_pp0_it2 <= ap_reg_ppstg_tmp_123_reg_1414_pp0_it1;
        ap_reg_ppstg_tmp_19_reg_1387_pp0_it2 <= ap_reg_ppstg_tmp_19_reg_1387_pp0_it1;
        ap_reg_ppstg_tmp_19_reg_1387_pp0_it3 <= ap_reg_ppstg_tmp_19_reg_1387_pp0_it2;
        ap_reg_ppstg_tmp_19_reg_1387_pp0_it4 <= ap_reg_ppstg_tmp_19_reg_1387_pp0_it3;
        ap_reg_ppstg_tmp_i_reg_1405_pp0_it2 <= ap_reg_ppstg_tmp_i_reg_1405_pp0_it1;
        src_kernel_win_0_val_0_1_6_reg_1483 <= src_kernel_win_0_val_0_1_fu_106;
        src_kernel_win_0_val_1_1_6_reg_1490 <= src_kernel_win_0_val_1_1_fu_122;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_col_assign_reg_1427_pp0_it1 <= col_assign_reg_1427;
        ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1 <= or_cond219_i_i_reg_1396;
        ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 <= or_cond2_reg_1419;
        ap_reg_ppstg_tmp_123_reg_1414_pp0_it1 <= tmp_123_reg_1414;
        ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 <= tmp_19_reg_1387;
        ap_reg_ppstg_tmp_29_reg_1423_pp0_it1 <= tmp_29_reg_1423;
        ap_reg_ppstg_tmp_i_reg_1405_pp0_it1 <= tmp_i_reg_1405;
        tmp_19_reg_1387 <= tmp_19_fu_638_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        brmerge_reg_1383 <= brmerge_fu_630_p2;
        locy_2_t_reg_1379 <= locy_2_t_fu_625_p2;
        sel_tmp3_reg_1364 <= sel_tmp3_fu_579_p2;
        sel_tmp4_reg_1369 <= sel_tmp4_fu_602_p2;
        sel_tmp7_reg_1374 <= sel_tmp7_fu_607_p2;
        sel_tmp8_reg_1359 <= sel_tmp8_fu_575_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_reg_1387) & (ap_const_lv1_0 == or_cond2_reg_1419) & (ap_const_lv1_0 == tmp_123_reg_1414) & (ap_const_lv1_0 == tmp_i_reg_1405))) begin
        col_assign_1_reg_1451 <= col_assign_1_fu_762_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_fu_638_p2) & ~(ap_const_lv1_0 == or_cond2_fu_723_p2) & (ap_const_lv1_0 == tmp_29_fu_729_p2))) begin
        col_assign_reg_1427 <= col_assign_fu_734_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) & ~(ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_3_fu_114 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_2_fu_174 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_1))) begin
        col_buf_0_val_0_0_5_fu_130 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_1_fu_170 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_6_fu_138 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_0_fu_166 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_48)) begin
        heightloop_reg_1240 <= heightloop_fu_324_p2;
        p_neg226_i_i_cast_reg_1255 <= p_neg226_i_i_cast_fu_350_p2;
        ref_cast_reg_1267[0] <= ref_cast_fu_362_p1[0];
ref_cast_reg_1267[1] <= ref_cast_fu_362_p1[1];
ref_cast_reg_1267[2] <= ref_cast_fu_362_p1[2];
ref_cast_reg_1267[3] <= ref_cast_fu_362_p1[3];
ref_cast_reg_1267[4] <= ref_cast_fu_362_p1[4];
ref_cast_reg_1267[5] <= ref_cast_fu_362_p1[5];
ref_cast_reg_1267[6] <= ref_cast_fu_362_p1[6];
ref_cast_reg_1267[7] <= ref_cast_fu_362_p1[7];
ref_cast_reg_1267[8] <= ref_cast_fu_362_p1[8];
ref_cast_reg_1267[9] <= ref_cast_fu_362_p1[9];
ref_cast_reg_1267[10] <= ref_cast_fu_362_p1[10];
        ref_reg_1261 <= ref_fu_356_p2;
        tmp_14_cast_reg_1250[0] <= tmp_14_cast_fu_342_p1[0];
tmp_14_cast_reg_1250[1] <= tmp_14_cast_fu_342_p1[1];
tmp_14_cast_reg_1250[2] <= tmp_14_cast_fu_342_p1[2];
tmp_14_cast_reg_1250[3] <= tmp_14_cast_fu_342_p1[3];
tmp_14_cast_reg_1250[4] <= tmp_14_cast_fu_342_p1[4];
tmp_14_cast_reg_1250[5] <= tmp_14_cast_fu_342_p1[5];
tmp_14_cast_reg_1250[6] <= tmp_14_cast_fu_342_p1[6];
tmp_14_cast_reg_1250[7] <= tmp_14_cast_fu_342_p1[7];
tmp_14_cast_reg_1250[8] <= tmp_14_cast_fu_342_p1[8];
tmp_14_cast_reg_1250[9] <= tmp_14_cast_fu_342_p1[9];
tmp_14_cast_reg_1250[10] <= tmp_14_cast_fu_342_p1[10];
        tmp_2_i1_reg_1277 <= tmp_2_i1_fu_376_p2;
        tmp_2_i_reg_1272 <= tmp_2_i_fu_366_p2;
        widthloop_reg_1245 <= widthloop_fu_330_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_1286 <= i_V_fu_391_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_reg_1387))) begin
        k_buf_0_val_0_addr_reg_1433 <= tmp_80_fu_755_p1;
        k_buf_0_val_1_addr_reg_1439 <= tmp_80_fu_755_p1;
        k_buf_0_val_2_addr_reg_1445 <= tmp_80_fu_755_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_fu_638_p2))) begin
        or_cond219_i_i_reg_1396 <= or_cond219_i_i_fu_665_p2;
        or_cond_i_reg_1409 <= or_cond_i_fu_703_p2;
        tmp_120_reg_1400 <= tmp_120_fu_676_p1;
        tmp_123_reg_1414 <= ImagLoc_x_fu_670_p2[ap_const_lv32_B];
        tmp_i_reg_1405 <= tmp_i_fu_698_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_fu_638_p2))) begin
        or_cond2_reg_1419 <= or_cond2_fu_723_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_16_fu_386_p2 == ap_const_lv1_0))) begin
        or_cond_i1_reg_1322 <= or_cond_i1_fu_506_p2;
        or_cond_i2_reg_1344 <= or_cond_i2_fu_553_p2;
        or_cond_reg_1301 <= or_cond_fu_436_p2;
        tmp_107_reg_1306 <= ImagLoc_y_fu_403_p2[ap_const_lv32_B];
        tmp_108_reg_1310 <= tmp_108_fu_457_p1;
        tmp_111_reg_1316 <= tmp_111_fu_473_p3;
        tmp_113_reg_1327 <= y_1_fu_481_p2[ap_const_lv32_B];
        tmp_114_reg_1332 <= tmp_114_fu_520_p1;
        tmp_115_reg_1337 <= tmp_115_fu_524_p1;
        tmp_117_reg_1349 <= y_1_1_fu_528_p2[ap_const_lv32_B];
        tmp_118_reg_1354 <= tmp_118_fu_567_p1;
        tmp_17_reg_1291 <= tmp_17_fu_397_p2;
        tmp_23_reg_1296 <= tmp_23_fu_409_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        right_border_buf_0_val_1_0_reg_1464 <= k_buf_0_val_1_q0;
        right_border_buf_0_val_2_0_reg_1457 <= k_buf_0_val_0_q0;
        src_kernel_win_0_val_2_0_reg_1471 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) & ~(ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) & (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_0)))) begin
        right_border_buf_0_val_1_2_1_fu_142 <= right_border_buf_0_val_1_2_8_fu_877_p3;
        right_border_buf_0_val_1_2_2_fu_146 <= right_border_buf_0_val_1_2_6_fu_868_p3;
        right_border_buf_0_val_1_2_7_fu_150 <= right_border_buf_0_val_1_2_4_fu_851_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3))) begin
        src_kernel_win_0_val_0_1_lo_reg_1511 <= src_kernel_win_0_val_0_1_fu_106;
        src_kernel_win_0_val_1_1_lo_reg_1517 <= src_kernel_win_0_val_1_1_fu_122;
        temp_0_i_i_i_057_i_i_1_1_1_reg_1523 <= temp_0_i_i_i_057_i_i_1_1_1_fu_1060_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it5) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it4))) begin
        src_kernel_win_0_val_0_2_fu_110 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4))) begin
        src_kernel_win_0_val_0_2_lo_reg_1529 <= src_kernel_win_0_val_0_2_fu_110;
        temp_0_i_i_i_057_i_i_1_1_2_reg_1534 <= temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3;
        tmp_139_2_reg_1539 <= tmp_139_2_fu_1080_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2))) begin
        src_kernel_win_0_val_1_2_fu_126 <= src_kernel_win_0_val_1_1_fu_122;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it2) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2))) begin
        src_kernel_win_0_val_1_2_lo_reg_1496 <= src_kernel_win_0_val_1_2_fu_126;
        temp_0_i_i_i_057_i_i_1_0_2_reg_1501 <= temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3;
        tmp_139_1_reg_1506 <= tmp_139_1_fu_1033_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        src_kernel_win_0_val_2_2_fu_134 <= src_kernel_win_0_val_2_1_fu_118;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1))) begin
        temp_0_i_i_i_057_i_i_1_0_1_reg_1477 <= temp_0_i_i_i_057_i_i_1_0_1_fu_910_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5))) begin
        temp_0_i_i_i_057_i_i_1_2_1_reg_1544 <= temp_0_i_i_i_057_i_i_1_2_1_fu_1100_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_19_fu_638_p2) & ~(ap_const_lv1_0 == or_cond2_fu_723_p2))) begin
        tmp_29_reg_1423 <= tmp_29_fu_729_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_done_reg or ap_sig_cseq_ST_st2_fsm_1 or tmp_16_fu_386_p2)
begin
    if (((ap_const_logic_1 == ap_done_reg) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_16_fu_386_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or tmp_16_fu_386_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_16_fu_386_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_3 assign process. ///
always @ (ap_sig_bdd_135)
begin
    if (ap_sig_bdd_135) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_4 assign process. ///
always @ (ap_sig_bdd_355)
begin
    if (ap_sig_bdd_355) begin
        ap_sig_cseq_ST_st12_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_24)
begin
    if (ap_sig_bdd_24) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_76)
begin
    if (ap_sig_bdd_76) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_116)
begin
    if (ap_sig_bdd_116) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_0_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce1 assign process. ///
always @ (ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_0_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_we1 assign process. ///
always @ (brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_0_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_1_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce1 assign process. ///
always @ (brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)))) begin
        k_buf_0_val_1_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_we1 assign process. ///
always @ (brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)))) begin
        k_buf_0_val_1_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_2_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce1 assign process. ///
always @ (brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)))) begin
        k_buf_0_val_2_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_we1 assign process. ///
always @ (brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)))) begin
        k_buf_0_val_2_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_we1 = ap_const_logic_0;
    end
end

/// p_dst_data_stream_V_write assign process. ///
always @ (ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_V_read assign process. ///
always @ (brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_CS_fsm or ap_sig_bdd_48 or tmp_16_fu_386_p2 or ap_sig_bdd_154 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it4 or ap_reg_ppiten_pp0_it6 or ap_sig_bdd_172 or ap_reg_ppiten_pp0_it7)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_48) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((tmp_16_fu_386_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_154 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_172 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it4)))) begin
                ap_NS_fsm = ap_ST_st12_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st12_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_670_p2 = ($signed(tmp_18_cast_fu_634_p1) + $signed(ap_const_lv12_FFF));
assign ImagLoc_y_fu_403_p2 = ($signed(tmp_15_cast_cast_fu_382_p1) + $signed(ap_const_lv12_FFC));

/// ap_sig_bdd_116 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_116 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_135 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_135 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_154 assign process. ///
always @ (p_src_data_stream_V_empty_n or brmerge_reg_1383 or ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 or ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)
begin
    ap_sig_bdd_154 = ((p_src_data_stream_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_19_reg_1387_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1383) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond2_reg_1419_pp0_it1));
end

/// ap_sig_bdd_172 assign process. ///
always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6)
begin
    ap_sig_bdd_172 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6));
end

/// ap_sig_bdd_24 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_24 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_355 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_355 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_48 assign process. ///
always @ (ap_start or ap_done_reg)
begin
    ap_sig_bdd_48 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end

/// ap_sig_bdd_76 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_76 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign brmerge_fu_630_p2 = (tmp_23_reg_1296 | or_cond_reg_1301);
assign col_assign_1_fu_762_p2 = (tmp_124_fu_751_p1 + p_neg226_i_i_cast_reg_1255);
assign col_assign_fu_734_p2 = (tmp_121_fu_680_p1 + p_neg226_i_i_cast_reg_1255);
assign col_buf_0_val_0_0_2_fu_976_p3 = ((sel_tmp_fu_971_p2)? col_buf_0_val_0_0_5_fu_130: col_buf_0_val_0_0_3_fu_114);
assign col_buf_0_val_0_0_9_fu_989_p3 = ((sel_tmp2_fu_984_p2)? col_buf_0_val_0_0_6_fu_138: col_buf_0_val_0_0_2_fu_976_p3);
assign heightloop_fu_324_p2 = (tmp_fu_316_p1 + ap_const_lv11_5);
assign i_V_fu_391_p2 = (p_012_0_i_i_reg_252 + ap_const_lv11_1);
assign icmp2_fu_659_p2 = (tmp_119_fu_649_p4 != ap_const_lv10_0? 1'b1: 1'b0);
assign icmp_fu_425_p2 = ($signed(tmp_106_fu_415_p4) > $signed(11'b00000000000)? 1'b1: 1'b0);
assign j_V_fu_643_p2 = (p_025_0_i_i_reg_263 + ap_const_lv11_1);
assign k_buf_0_val_0_address0 = tmp_80_fu_755_p1;
assign k_buf_0_val_0_address1 = k_buf_0_val_0_addr_reg_1433;
assign k_buf_0_val_0_d1 = p_src_data_stream_V_dout;
assign k_buf_0_val_1_address0 = tmp_80_fu_755_p1;
assign k_buf_0_val_1_address1 = k_buf_0_val_1_addr_reg_1439;
assign k_buf_0_val_1_d1 = k_buf_0_val_0_q0;
assign k_buf_0_val_2_address0 = tmp_80_fu_755_p1;
assign k_buf_0_val_2_address1 = k_buf_0_val_2_addr_reg_1445;
assign k_buf_0_val_2_d1 = k_buf_0_val_1_q0;
assign locy_1_t_fu_597_p2 = (tmp_115_reg_1337 - tmp_81_fu_591_p3);
assign locy_2_t_fu_625_p2 = (tmp_115_reg_1337 - tmp_83_fu_619_p3);
assign locy_fu_571_p2 = (tmp_108_reg_1310 - tmp_111_reg_1316);
assign or_cond219_i_i_fu_665_p2 = (tmp_17_reg_1291 & icmp2_fu_659_p2);
assign or_cond2_fu_723_p2 = (tmp_26_fu_717_p2 & tmp_i_fu_698_p2);
assign or_cond_fu_436_p2 = (icmp_fu_425_p2 & tmp_25_fu_431_p2);
assign or_cond_i1_fu_506_p2 = (tmp_i1_fu_501_p2 & rev_fu_495_p2);
assign or_cond_i2_fu_553_p2 = (tmp_i2_fu_548_p2 & rev1_fu_542_p2);
assign or_cond_i_fu_703_p2 = (tmp_i_fu_698_p2 & rev2_fu_692_p2);
assign p_assign_1_i_fu_745_p3 = ((or_cond_i_reg_1409)? tmp_120_reg_1400: p_assign_fu_739_p3);
assign p_assign_fu_739_p3 = ((tmp_123_reg_1414)? ap_const_lv11_0: tmp_2_i_reg_1272);
assign p_dst_data_stream_V_din = ((tmp_139_2_2_fu_1107_p2)? ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6: temp_0_i_i_i_057_i_i_1_2_1_reg_1544);
assign p_i_i_fu_450_p3 = ((tmp_25_fu_431_p2)? ap_const_lv11_2: ref_reg_1261);
assign p_neg226_i_i_cast_fu_350_p2 = (tmp_104_fu_346_p1 ^ ap_const_lv2_3);
assign ref_cast_fu_362_p1 = ref_fu_356_p2;
assign ref_fu_356_p2 = ($signed(tmp_fu_316_p1) + $signed(ap_const_lv11_7FF));
assign rev1_fu_542_p2 = (tmp_116_fu_534_p3 ^ ap_const_lv1_1);
assign rev2_fu_692_p2 = (tmp_122_fu_684_p3 ^ ap_const_lv1_1);
assign rev_fu_495_p2 = (tmp_112_fu_487_p3 ^ ap_const_lv1_1);
assign right_border_buf_0_val_1_2_11_fu_1006_p3 = ((sel_tmp2_fu_984_p2)? right_border_buf_0_val_1_2_1_fu_142: right_border_buf_0_val_1_2_fu_998_p3);
assign right_border_buf_0_val_1_2_3_fu_838_p3 = ((sel_tmp1_fu_833_p2)? right_border_buf_0_val_1_2_7_fu_150: k_buf_0_val_1_q0);
assign right_border_buf_0_val_1_2_4_fu_851_p3 = ((sel_tmp5_fu_846_p2)? right_border_buf_0_val_1_2_7_fu_150: right_border_buf_0_val_1_2_3_fu_838_p3);
assign right_border_buf_0_val_1_2_5_fu_860_p3 = ((sel_tmp1_fu_833_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_2_fu_146);
assign right_border_buf_0_val_1_2_6_fu_868_p3 = ((sel_tmp5_fu_846_p2)? right_border_buf_0_val_1_2_2_fu_146: right_border_buf_0_val_1_2_5_fu_860_p3);
assign right_border_buf_0_val_1_2_8_fu_877_p3 = ((sel_tmp5_fu_846_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_1_fu_142);
assign right_border_buf_0_val_1_2_fu_998_p3 = ((sel_tmp_fu_971_p2)? right_border_buf_0_val_1_2_2_fu_146: right_border_buf_0_val_1_2_7_fu_150);
assign sel_tmp1_fu_833_p2 = (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp2_fu_984_p2 = (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp3_fu_579_p2 = (locy_fu_571_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp4_fu_602_p2 = (tmp_115_reg_1337 == tmp_81_fu_591_p3? 1'b1: 1'b0);
assign sel_tmp5_fu_846_p2 = (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp6_fu_941_p3 = ((sel_tmp4_reg_1369)? right_border_buf_0_val_2_0_reg_1457: src_kernel_win_0_val_2_0_reg_1471);
assign sel_tmp7_fu_607_p2 = (locy_1_t_fu_597_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp8_fu_575_p2 = (tmp_108_reg_1310 == tmp_111_reg_1316? 1'b1: 1'b0);
assign sel_tmp9_fu_929_p3 = ((sel_tmp8_reg_1359)? right_border_buf_0_val_2_0_reg_1457: src_kernel_win_0_val_2_0_reg_1471);
assign sel_tmp_fu_971_p2 = (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 == ap_const_lv2_1? 1'b1: 1'b0);
assign src_kernel_win_0_val_0_0_fu_934_p3 = ((sel_tmp3_reg_1364)? right_border_buf_0_val_1_0_reg_1464: sel_tmp9_fu_929_p3);
assign src_kernel_win_0_val_1_0_fu_946_p3 = ((sel_tmp7_reg_1374)? right_border_buf_0_val_1_0_reg_1464: sel_tmp6_fu_941_p3);
assign temp_0_i_i_i_057_i_i_1_0_1_fu_910_p3 = ((tmp_139_0_1_fu_904_p2)? src_kernel_win_0_val_2_1_fu_118: src_kernel_win_0_val_2_2_fu_134);
assign temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3 = ((tmp_139_0_2_fu_1021_p2)? src_kernel_win_0_val_2_1_fu_118: temp_0_i_i_i_057_i_i_1_0_1_reg_1477);
assign temp_0_i_i_i_057_i_i_1_1_1_fu_1060_p3 = ((tmp_139_1_1_fu_1055_p2)? src_kernel_win_0_val_1_1_6_reg_1490: temp_0_i_i_i_057_i_i_1_1_fu_1050_p3);
assign temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3 = ((tmp_139_1_2_fu_1070_p2)? src_kernel_win_0_val_1_1_lo_reg_1517: temp_0_i_i_i_057_i_i_1_1_1_reg_1523);
assign temp_0_i_i_i_057_i_i_1_1_fu_1050_p3 = ((tmp_139_1_reg_1506)? src_kernel_win_0_val_1_2_lo_reg_1496: temp_0_i_i_i_057_i_i_1_0_2_reg_1501);
assign temp_0_i_i_i_057_i_i_1_2_1_fu_1100_p3 = ((tmp_139_2_1_fu_1095_p2)? ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5: temp_0_i_i_i_057_i_i_1_2_fu_1090_p3);
assign temp_0_i_i_i_057_i_i_1_2_fu_1090_p3 = ((tmp_139_2_reg_1539)? src_kernel_win_0_val_0_2_lo_reg_1529: temp_0_i_i_i_057_i_i_1_1_2_reg_1534);
assign tmp_103_fu_320_p1 = p_src_cols_V_read[10:0];
assign tmp_104_fu_346_p1 = p_src_cols_V_read[1:0];
assign tmp_105_fu_372_p1 = p_src_rows_V_read[1:0];
assign tmp_106_fu_415_p4 = {{ImagLoc_y_fu_403_p2[ap_const_lv32_B : ap_const_lv32_1]}};
assign tmp_108_fu_457_p1 = p_i_i_fu_450_p3[1:0];
assign tmp_109_fu_466_p1 = ImagLoc_y_fu_403_p2[1:0];
assign tmp_110_fu_470_p1 = ref_reg_1261[1:0];
assign tmp_111_fu_473_p3 = ((tmp_i5_fu_461_p2)? tmp_109_fu_466_p1: tmp_110_fu_470_p1);
assign tmp_112_fu_487_p3 = y_1_fu_481_p2[ap_const_lv32_B];
assign tmp_114_fu_520_p1 = y_1_fu_481_p2[1:0];
assign tmp_115_fu_524_p1 = p_i_i_fu_450_p3[1:0];
assign tmp_116_fu_534_p3 = y_1_1_fu_528_p2[ap_const_lv32_B];
assign tmp_118_fu_567_p1 = y_1_1_fu_528_p2[1:0];
assign tmp_119_fu_649_p4 = {{p_025_0_i_i_reg_263[ap_const_lv32_A : ap_const_lv32_1]}};
assign tmp_120_fu_676_p1 = ImagLoc_x_fu_670_p2[10:0];
assign tmp_121_fu_680_p1 = ImagLoc_x_fu_670_p2[1:0];
assign tmp_122_fu_684_p3 = ImagLoc_x_fu_670_p2[ap_const_lv32_B];
assign tmp_124_fu_751_p1 = p_assign_1_i_fu_745_p3[1:0];
assign tmp_139_0_1_fu_904_p2 = (src_kernel_win_0_val_2_1_fu_118 > src_kernel_win_0_val_2_2_fu_134? 1'b1: 1'b0);
assign tmp_139_0_2_fu_1021_p2 = (src_kernel_win_0_val_2_1_fu_118 > temp_0_i_i_i_057_i_i_1_0_1_reg_1477? 1'b1: 1'b0);
assign tmp_139_1_1_fu_1055_p2 = (src_kernel_win_0_val_1_1_6_reg_1490 > temp_0_i_i_i_057_i_i_1_1_fu_1050_p3? 1'b1: 1'b0);
assign tmp_139_1_2_fu_1070_p2 = (src_kernel_win_0_val_1_1_lo_reg_1517 > temp_0_i_i_i_057_i_i_1_1_1_reg_1523? 1'b1: 1'b0);
assign tmp_139_1_fu_1033_p2 = (src_kernel_win_0_val_1_2_fu_126 > temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3? 1'b1: 1'b0);
assign tmp_139_2_1_fu_1095_p2 = (ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5 > temp_0_i_i_i_057_i_i_1_2_fu_1090_p3? 1'b1: 1'b0);
assign tmp_139_2_2_fu_1107_p2 = (ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6 > temp_0_i_i_i_057_i_i_1_2_1_reg_1544? 1'b1: 1'b0);
assign tmp_139_2_fu_1080_p2 = (src_kernel_win_0_val_0_2_fu_110 > temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3? 1'b1: 1'b0);
assign tmp_14_cast_fu_342_p1 = tmp_14_fu_336_p2;
assign tmp_14_fu_336_p2 = ($signed(tmp_103_fu_320_p1) + $signed(ap_const_lv11_7FD));
assign tmp_15_cast_cast_fu_382_p1 = p_012_0_i_i_reg_252;
assign tmp_16_fu_386_p2 = (p_012_0_i_i_reg_252 < heightloop_reg_1240? 1'b1: 1'b0);
assign tmp_17_fu_397_p2 = (p_012_0_i_i_reg_252 > ap_const_lv11_4? 1'b1: 1'b0);
assign tmp_18_cast_fu_634_p1 = p_025_0_i_i_reg_263;
assign tmp_19_fu_638_p2 = (p_025_0_i_i_reg_263 < widthloop_reg_1245? 1'b1: 1'b0);
assign tmp_23_fu_409_p2 = ($signed(ImagLoc_y_fu_403_p2) < $signed(12'b111111111111)? 1'b1: 1'b0);
assign tmp_25_fu_431_p2 = ($signed(ImagLoc_y_fu_403_p2) < $signed(ref_cast_reg_1267)? 1'b1: 1'b0);
assign tmp_26_fu_717_p2 = (p_025_0_i_i_reg_263 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_29_fu_729_p2 = ($signed(ImagLoc_x_fu_670_p2) < $signed(tmp_14_cast_reg_1250)? 1'b1: 1'b0);
assign tmp_2_i1_fu_376_p2 = ($signed(tmp_105_fu_372_p1) + $signed(ap_const_lv2_3));
assign tmp_2_i_fu_366_p2 = ($signed(tmp_103_fu_320_p1) + $signed(ap_const_lv11_7FF));
assign tmp_80_fu_755_p1 = p_assign_1_i_fu_745_p3;
assign tmp_81_fu_591_p3 = ((or_cond_i1_reg_1322)? tmp_114_reg_1332: tmp_s_fu_585_p3);
assign tmp_82_fu_613_p3 = ((tmp_117_reg_1349)? ap_const_lv2_0: tmp_2_i1_reg_1277);
assign tmp_83_fu_619_p3 = ((or_cond_i2_reg_1344)? tmp_118_reg_1354: tmp_82_fu_613_p3);
assign tmp_fu_316_p1 = p_src_rows_V_read[10:0];
assign tmp_i1_fu_501_p2 = ($signed(y_1_fu_481_p2) < $signed(p_src_rows_V_read)? 1'b1: 1'b0);
assign tmp_i2_fu_548_p2 = ($signed(y_1_1_fu_528_p2) < $signed(p_src_rows_V_read)? 1'b1: 1'b0);
assign tmp_i5_fu_461_p2 = ($signed(ImagLoc_y_fu_403_p2) < $signed(p_src_rows_V_read)? 1'b1: 1'b0);
assign tmp_i_fu_698_p2 = ($signed(ImagLoc_x_fu_670_p2) < $signed(p_src_cols_V_read)? 1'b1: 1'b0);
assign tmp_s_fu_585_p3 = ((tmp_113_reg_1327)? ap_const_lv2_0: tmp_2_i1_reg_1277);
assign widthloop_fu_330_p2 = (tmp_103_fu_320_p1 + ap_const_lv11_2);
assign y_1_1_fu_528_p2 = ($signed(tmp_15_cast_cast_fu_382_p1) + $signed(ap_const_lv12_FFA));
assign y_1_fu_481_p2 = ($signed(tmp_15_cast_cast_fu_382_p1) + $signed(ap_const_lv12_FFB));
always @ (posedge ap_clk)
begin
    tmp_14_cast_reg_1250[11] <= 1'b0;
    ref_cast_reg_1267[11] <= 1'b0;
end



endmodule //image_filter_Dilate_0_0_1080_1920_s

