-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_Dilate_0_0_1080_1920_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of image_filter_Dilate_0_0_1080_1920_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_pp0_stg0_fsm_3 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_st12_fsm_4 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv11_5 : STD_LOGIC_VECTOR (10 downto 0) := "00000000101";
    constant ap_const_lv11_2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_const_lv11_7FD : STD_LOGIC_VECTOR (10 downto 0) := "11111111101";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv11_4 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_const_lv12_FFC : STD_LOGIC_VECTOR (11 downto 0) := "111111111100";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_FFB : STD_LOGIC_VECTOR (11 downto 0) := "111111111011";
    constant ap_const_lv12_FFA : STD_LOGIC_VECTOR (11 downto 0) := "111111111010";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_24 : BOOLEAN;
    signal p_025_0_i_i_reg_263 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_bdd_48 : BOOLEAN;
    signal heightloop_fu_324_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal heightloop_reg_1240 : STD_LOGIC_VECTOR (10 downto 0);
    signal widthloop_fu_330_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal widthloop_reg_1245 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_14_cast_fu_342_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_14_cast_reg_1250 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_neg226_i_i_cast_fu_350_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_neg226_i_i_cast_reg_1255 : STD_LOGIC_VECTOR (1 downto 0);
    signal ref_fu_356_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ref_reg_1261 : STD_LOGIC_VECTOR (10 downto 0);
    signal ref_cast_fu_362_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ref_cast_reg_1267 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_i_fu_366_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_i_reg_1272 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_i1_fu_376_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_i1_reg_1277 : STD_LOGIC_VECTOR (1 downto 0);
    signal i_V_fu_391_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_V_reg_1286 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_76 : BOOLEAN;
    signal tmp_17_fu_397_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1291 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_reg_1296 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_reg_1301 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_107_reg_1306 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_108_fu_457_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_108_reg_1310 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_111_fu_473_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_111_reg_1316 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_cond_i1_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i1_reg_1322 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_113_reg_1327 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_114_fu_520_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_114_reg_1332 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_115_fu_524_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_115_reg_1337 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_cond_i2_fu_553_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i2_reg_1344 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_117_reg_1349 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_118_fu_567_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_118_reg_1354 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp8_fu_575_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_reg_1359 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_116 : BOOLEAN;
    signal sel_tmp3_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_reg_1364 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_reg_1369 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_reg_1374 : STD_LOGIC_VECTOR (0 downto 0);
    signal locy_2_t_fu_625_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal locy_2_t_reg_1379 : STD_LOGIC_VECTOR (1 downto 0);
    signal brmerge_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1383 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_1387 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_3 : STD_LOGIC;
    signal ap_sig_bdd_135 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_154 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it2 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it3 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it4 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it5 : STD_LOGIC := '0';
    signal ap_reg_ppiten_pp0_it6 : STD_LOGIC := '0';
    signal or_cond219_i_i_reg_1396 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_bdd_172 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it7 : STD_LOGIC := '0';
    signal ap_reg_ppstg_tmp_19_reg_1387_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_19_reg_1387_pp0_it3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_19_reg_1387_pp0_it4 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_643_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_cond219_i_i_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_120_fu_676_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_120_reg_1400 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_1405 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_i_reg_1405_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_i_reg_1405_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_703_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1409 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_123_reg_1414 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_123_reg_1414_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_123_reg_1414_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_723_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_or_cond2_reg_1419_pp0_it2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_fu_729_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_1423 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_ppstg_tmp_29_reg_1423_pp0_it1 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_assign_fu_734_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_assign_reg_1427 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_reg_ppstg_col_assign_reg_1427_pp0_it1 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_0_addr_reg_1433 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_1_addr_reg_1439 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_2_addr_reg_1445 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_assign_1_fu_762_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_assign_1_reg_1451 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_2_0_reg_1457 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_0_reg_1464 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_0_reg_1471 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_0_1_fu_910_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_0_1_reg_1477 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_1_6_reg_1483 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_6_reg_1490 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_2_lo_reg_1496 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_0_2_reg_1501 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_139_1_fu_1033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_1_reg_1506 : STD_LOGIC_VECTOR (0 downto 0);
    signal src_kernel_win_0_val_0_1_lo_reg_1511 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it5 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_lo_reg_1517 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_1_1_fu_1060_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_1_1_reg_1523 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_2_lo_reg_1529 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_1_2_reg_1534 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_139_2_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_2_reg_1539 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_0_i_i_i_057_i_i_1_2_1_fu_1100_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal temp_0_i_i_i_057_i_i_1_2_1_reg_1544 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_0_ce0 : STD_LOGIC;
    signal k_buf_0_val_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_0_ce1 : STD_LOGIC;
    signal k_buf_0_val_0_we1 : STD_LOGIC;
    signal k_buf_0_val_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_1_ce0 : STD_LOGIC;
    signal k_buf_0_val_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_1_ce1 : STD_LOGIC;
    signal k_buf_0_val_1_we1 : STD_LOGIC;
    signal k_buf_0_val_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_2_ce0 : STD_LOGIC;
    signal k_buf_0_val_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_2_ce1 : STD_LOGIC;
    signal k_buf_0_val_2_we1 : STD_LOGIC;
    signal k_buf_0_val_2_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_012_0_i_i_reg_252 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_cseq_ST_st12_fsm_4 : STD_LOGIC;
    signal ap_sig_bdd_355 : BOOLEAN;
    signal tmp_80_fu_755_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal src_kernel_win_0_val_0_1_fu_106 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_0_fu_934_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_9_fu_989_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_0_2_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_3_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_1_fu_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_1_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_0_fu_946_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_11_fu_1006_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_1_2_fu_126 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_5_fu_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_val_2_2_fu_134 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_6_fu_138 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_1_fu_142 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_8_fu_877_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_2_fu_146 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_6_fu_868_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_7_fu_150 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_4_fu_851_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_0_fu_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_1_fu_170 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_0_2_fu_174 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_316_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_103_fu_320_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_14_fu_336_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_104_fu_346_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_105_fu_372_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_cast_cast_fu_382_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_y_fu_403_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_106_fu_415_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_431_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_i_i_fu_450_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i5_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_109_fu_466_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_110_fu_470_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_1_fu_481_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_112_fu_487_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i1_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_1_1_fu_528_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_116_fu_534_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i2_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev1_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal locy_fu_571_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_s_fu_585_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_81_fu_591_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal locy_1_t_fu_597_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_82_fu_613_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_83_fu_619_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_119_fu_649_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp2_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_cast_fu_634_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_fu_670_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_122_fu_684_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev2_fu_692_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_121_fu_680_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_fu_739_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_assign_1_i_fu_745_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_124_fu_751_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sel_tmp1_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_846_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal right_border_buf_0_val_1_2_3_fu_838_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_5_fu_860_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_139_0_1_fu_904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_929_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp6_fu_941_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp_fu_971_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_984_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_buf_0_val_0_0_2_fu_976_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_val_1_2_fu_998_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_139_0_2_fu_1021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_0_i_i_i_057_i_i_1_1_fu_1050_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_139_1_1_fu_1055_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_1_2_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal temp_0_i_i_i_057_i_i_1_2_fu_1090_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_139_2_1_fu_1095_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_139_2_2_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component image_filter_FAST_t_opr_k_buf_val_0_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_0_U : component image_filter_FAST_t_opr_k_buf_val_0_V
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_0_address0,
        ce0 => k_buf_0_val_0_ce0,
        q0 => k_buf_0_val_0_q0,
        address1 => k_buf_0_val_0_address1,
        ce1 => k_buf_0_val_0_ce1,
        we1 => k_buf_0_val_0_we1,
        d1 => k_buf_0_val_0_d1);

    k_buf_0_val_1_U : component image_filter_FAST_t_opr_k_buf_val_0_V
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_1_address0,
        ce0 => k_buf_0_val_1_ce0,
        q0 => k_buf_0_val_1_q0,
        address1 => k_buf_0_val_1_address1,
        ce1 => k_buf_0_val_1_ce1,
        we1 => k_buf_0_val_1_we1,
        d1 => k_buf_0_val_1_d1);

    k_buf_0_val_2_U : component image_filter_FAST_t_opr_k_buf_val_0_V
    generic map (
        DataWidth => 8,
        AddressRange => 1920,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_2_address0,
        ce0 => k_buf_0_val_2_ce0,
        q0 => k_buf_0_val_2_q0,
        address1 => k_buf_0_val_2_address1,
        ce1 => k_buf_0_val_2_ce1,
        we1 => k_buf_0_val_2_we1,
        d1 => k_buf_0_val_2_d1);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_16_fu_386_p2 = ap_const_lv1_0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = tmp_19_fu_638_p2))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it2 assign process. --
    ap_reg_ppiten_pp0_it2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then 
                    ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it3 assign process. --
    ap_reg_ppiten_pp0_it3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then 
                    ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it4 assign process. --
    ap_reg_ppiten_pp0_it4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then
                    if (not((ap_const_logic_1 = ap_reg_ppiten_pp0_it2))) then 
                        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
                    elsif ((ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) then 
                        ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it5 assign process. --
    ap_reg_ppiten_pp0_it5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then 
                    ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it6 assign process. --
    ap_reg_ppiten_pp0_it6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then 
                    ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it7 assign process. --
    ap_reg_ppiten_pp0_it7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
            else
                if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then 
                    ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
                elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                    ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- p_012_0_i_i_reg_252 assign process. --
    p_012_0_i_i_reg_252_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st12_fsm_4)) then 
                p_012_0_i_i_reg_252 <= i_V_reg_1286;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_48))) then 
                p_012_0_i_i_reg_252 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    -- p_025_0_i_i_reg_263 assign process. --
    p_025_0_i_i_reg_263_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_fu_638_p2)))) then 
                p_025_0_i_i_reg_263 <= j_V_fu_643_p2;
            elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                p_025_0_i_i_reg_263 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    -- src_kernel_win_0_val_0_1_fu_106 assign process. --
    src_kernel_win_0_val_0_1_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2))) or (not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2))))) then 
                src_kernel_win_0_val_0_1_fu_106 <= right_border_buf_0_val_2_0_reg_1457;
            elsif (((not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) and (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) and (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_0)) or (not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) and not((ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_1)) and not((ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_0_1_fu_106 <= col_buf_0_val_0_0_9_fu_989_p3;
            elsif ((((ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = tmp_107_reg_1306) and (locy_2_t_reg_1379 = ap_const_lv2_1)) or ((ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = tmp_107_reg_1306) and (locy_2_t_reg_1379 = ap_const_lv2_0)) or ((ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = tmp_107_reg_1306) and not((locy_2_t_reg_1379 = ap_const_lv2_1)) and not((locy_2_t_reg_1379 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_0_1_fu_106 <= src_kernel_win_0_val_0_0_fu_934_p3;
            end if; 
        end if;
    end process;

    -- src_kernel_win_0_val_1_1_fu_122 assign process. --
    src_kernel_win_0_val_1_1_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2))) or (not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2))))) then 
                src_kernel_win_0_val_1_1_fu_122 <= right_border_buf_0_val_1_0_reg_1464;
            elsif (((not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) and (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) and (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_0)) or (not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it2) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it2) and not((ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_1)) and not((ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_1_1_fu_122 <= right_border_buf_0_val_1_2_11_fu_1006_p3;
            elsif ((((ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = tmp_107_reg_1306) and (locy_2_t_reg_1379 = ap_const_lv2_1)) or ((ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = tmp_107_reg_1306) and (locy_2_t_reg_1379 = ap_const_lv2_0)) or ((ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and (ap_const_lv1_0 = tmp_107_reg_1306) and not((locy_2_t_reg_1379 = ap_const_lv2_1)) and not((locy_2_t_reg_1379 = ap_const_lv2_0))))) then 
                src_kernel_win_0_val_1_1_fu_122 <= src_kernel_win_0_val_1_0_fu_946_p3;
            end if; 
        end if;
    end process;

    -- src_kernel_win_0_val_2_1_fu_118 assign process. --
    src_kernel_win_0_val_2_1_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it1) and not((col_assign_1_reg_1451 = ap_const_lv2_1)) and not((col_assign_1_reg_1451 = ap_const_lv2_0)))) then 
                src_kernel_win_0_val_2_1_fu_118 <= right_border_buf_0_val_0_2_fu_174;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it1) and (col_assign_1_reg_1451 = ap_const_lv2_0))) then 
                src_kernel_win_0_val_2_1_fu_118 <= right_border_buf_0_val_0_0_fu_166;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it1) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_i_reg_1405_pp0_it1) and (col_assign_1_reg_1451 = ap_const_lv2_1))) then 
                src_kernel_win_0_val_2_1_fu_118 <= right_border_buf_0_val_0_1_fu_170;
            elsif (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = tmp_107_reg_1306) and not((locy_2_t_reg_1379 = ap_const_lv2_1)) and not((locy_2_t_reg_1379 = ap_const_lv2_0))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and (ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_123_reg_1414_pp0_it1))))) then 
                src_kernel_win_0_val_2_1_fu_118 <= k_buf_0_val_2_q0;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = tmp_107_reg_1306) and (locy_2_t_reg_1379 = ap_const_lv2_0))) then 
                src_kernel_win_0_val_2_1_fu_118 <= k_buf_0_val_0_q0;
            elsif ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and (ap_const_lv1_0 = brmerge_reg_1383) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = tmp_107_reg_1306) and (locy_2_t_reg_1379 = ap_const_lv2_1))) then 
                src_kernel_win_0_val_2_1_fu_118 <= k_buf_0_val_1_q0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))) then
                ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 <= col_assign_1_reg_1451;
                ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1;
                ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2;
                ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3;
                ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4;
                ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6 <= ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5;
                ap_reg_ppstg_or_cond2_reg_1419_pp0_it2 <= ap_reg_ppstg_or_cond2_reg_1419_pp0_it1;
                ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4 <= src_kernel_win_0_val_0_1_6_reg_1483;
                ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4;
                ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it5 <= src_kernel_win_0_val_0_1_lo_reg_1511;
                ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it5;
                ap_reg_ppstg_tmp_123_reg_1414_pp0_it2 <= ap_reg_ppstg_tmp_123_reg_1414_pp0_it1;
                ap_reg_ppstg_tmp_19_reg_1387_pp0_it2 <= ap_reg_ppstg_tmp_19_reg_1387_pp0_it1;
                ap_reg_ppstg_tmp_19_reg_1387_pp0_it3 <= ap_reg_ppstg_tmp_19_reg_1387_pp0_it2;
                ap_reg_ppstg_tmp_19_reg_1387_pp0_it4 <= ap_reg_ppstg_tmp_19_reg_1387_pp0_it3;
                ap_reg_ppstg_tmp_i_reg_1405_pp0_it2 <= ap_reg_ppstg_tmp_i_reg_1405_pp0_it1;
                src_kernel_win_0_val_0_1_6_reg_1483 <= src_kernel_win_0_val_0_1_fu_106;
                src_kernel_win_0_val_1_1_6_reg_1490 <= src_kernel_win_0_val_1_1_fu_122;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then
                ap_reg_ppstg_col_assign_reg_1427_pp0_it1 <= col_assign_reg_1427;
                ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1 <= or_cond219_i_i_reg_1396;
                ap_reg_ppstg_or_cond2_reg_1419_pp0_it1 <= or_cond2_reg_1419;
                ap_reg_ppstg_tmp_123_reg_1414_pp0_it1 <= tmp_123_reg_1414;
                ap_reg_ppstg_tmp_19_reg_1387_pp0_it1 <= tmp_19_reg_1387;
                ap_reg_ppstg_tmp_29_reg_1423_pp0_it1 <= tmp_29_reg_1423;
                ap_reg_ppstg_tmp_i_reg_1405_pp0_it1 <= tmp_i_reg_1405;
                tmp_19_reg_1387 <= tmp_19_fu_638_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                brmerge_reg_1383 <= brmerge_fu_630_p2;
                locy_2_t_reg_1379 <= locy_2_t_fu_625_p2;
                sel_tmp3_reg_1364 <= sel_tmp3_fu_579_p2;
                sel_tmp4_reg_1369 <= sel_tmp4_fu_602_p2;
                sel_tmp7_reg_1374 <= sel_tmp7_fu_607_p2;
                sel_tmp8_reg_1359 <= sel_tmp8_fu_575_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_reg_1387)) and (ap_const_lv1_0 = or_cond2_reg_1419) and (ap_const_lv1_0 = tmp_123_reg_1414) and (ap_const_lv1_0 = tmp_i_reg_1405))) then
                col_assign_1_reg_1451 <= col_assign_1_fu_762_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_fu_638_p2)) and not((ap_const_lv1_0 = or_cond2_fu_723_p2)) and (ap_const_lv1_0 = tmp_29_fu_729_p2))) then
                col_assign_reg_1427 <= col_assign_fu_734_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) and not((ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_1)) and not((ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_0)))) then
                col_buf_0_val_0_0_3_fu_114 <= k_buf_0_val_0_q0;
                right_border_buf_0_val_0_2_fu_174 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_1))) then
                col_buf_0_val_0_0_5_fu_130 <= k_buf_0_val_0_q0;
                right_border_buf_0_val_0_1_fu_170 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_0))) then
                col_buf_0_val_0_0_6_fu_138 <= k_buf_0_val_0_q0;
                right_border_buf_0_val_0_0_fu_166 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_48))) then
                heightloop_reg_1240 <= heightloop_fu_324_p2;
                p_neg226_i_i_cast_reg_1255 <= p_neg226_i_i_cast_fu_350_p2;
                ref_cast_reg_1267(0) <= ref_cast_fu_362_p1(0);
    ref_cast_reg_1267(1) <= ref_cast_fu_362_p1(1);
    ref_cast_reg_1267(2) <= ref_cast_fu_362_p1(2);
    ref_cast_reg_1267(3) <= ref_cast_fu_362_p1(3);
    ref_cast_reg_1267(4) <= ref_cast_fu_362_p1(4);
    ref_cast_reg_1267(5) <= ref_cast_fu_362_p1(5);
    ref_cast_reg_1267(6) <= ref_cast_fu_362_p1(6);
    ref_cast_reg_1267(7) <= ref_cast_fu_362_p1(7);
    ref_cast_reg_1267(8) <= ref_cast_fu_362_p1(8);
    ref_cast_reg_1267(9) <= ref_cast_fu_362_p1(9);
    ref_cast_reg_1267(10) <= ref_cast_fu_362_p1(10);
                ref_reg_1261 <= ref_fu_356_p2;
                tmp_14_cast_reg_1250(0) <= tmp_14_cast_fu_342_p1(0);
    tmp_14_cast_reg_1250(1) <= tmp_14_cast_fu_342_p1(1);
    tmp_14_cast_reg_1250(2) <= tmp_14_cast_fu_342_p1(2);
    tmp_14_cast_reg_1250(3) <= tmp_14_cast_fu_342_p1(3);
    tmp_14_cast_reg_1250(4) <= tmp_14_cast_fu_342_p1(4);
    tmp_14_cast_reg_1250(5) <= tmp_14_cast_fu_342_p1(5);
    tmp_14_cast_reg_1250(6) <= tmp_14_cast_fu_342_p1(6);
    tmp_14_cast_reg_1250(7) <= tmp_14_cast_fu_342_p1(7);
    tmp_14_cast_reg_1250(8) <= tmp_14_cast_fu_342_p1(8);
    tmp_14_cast_reg_1250(9) <= tmp_14_cast_fu_342_p1(9);
    tmp_14_cast_reg_1250(10) <= tmp_14_cast_fu_342_p1(10);
                tmp_2_i1_reg_1277 <= tmp_2_i1_fu_376_p2;
                tmp_2_i_reg_1272 <= tmp_2_i_fu_366_p2;
                widthloop_reg_1245 <= widthloop_fu_330_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                i_V_reg_1286 <= i_V_fu_391_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_reg_1387)))) then
                k_buf_0_val_0_addr_reg_1433 <= tmp_80_fu_755_p1(11 - 1 downto 0);
                k_buf_0_val_1_addr_reg_1439 <= tmp_80_fu_755_p1(11 - 1 downto 0);
                k_buf_0_val_2_addr_reg_1445 <= tmp_80_fu_755_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_fu_638_p2)))) then
                or_cond219_i_i_reg_1396 <= or_cond219_i_i_fu_665_p2;
                or_cond_i_reg_1409 <= or_cond_i_fu_703_p2;
                tmp_120_reg_1400 <= tmp_120_fu_676_p1;
                tmp_123_reg_1414 <= ImagLoc_x_fu_670_p2(11 downto 11);
                tmp_i_reg_1405 <= tmp_i_fu_698_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_fu_638_p2)))) then
                or_cond2_reg_1419 <= or_cond2_fu_723_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((tmp_16_fu_386_p2 = ap_const_lv1_0)))) then
                or_cond_i1_reg_1322 <= or_cond_i1_fu_506_p2;
                or_cond_i2_reg_1344 <= or_cond_i2_fu_553_p2;
                or_cond_reg_1301 <= or_cond_fu_436_p2;
                tmp_107_reg_1306 <= ImagLoc_y_fu_403_p2(11 downto 11);
                tmp_108_reg_1310 <= tmp_108_fu_457_p1;
                tmp_111_reg_1316 <= tmp_111_fu_473_p3;
                tmp_113_reg_1327 <= y_1_fu_481_p2(11 downto 11);
                tmp_114_reg_1332 <= tmp_114_fu_520_p1;
                tmp_115_reg_1337 <= tmp_115_fu_524_p1;
                tmp_117_reg_1349 <= y_1_1_fu_528_p2(11 downto 11);
                tmp_118_reg_1354 <= tmp_118_fu_567_p1;
                tmp_17_reg_1291 <= tmp_17_fu_397_p2;
                tmp_23_reg_1296 <= tmp_23_fu_409_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then
                right_border_buf_0_val_1_0_reg_1464 <= k_buf_0_val_1_q0;
                right_border_buf_0_val_2_0_reg_1457 <= k_buf_0_val_0_q0;
                src_kernel_win_0_val_2_0_reg_1471 <= k_buf_0_val_2_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) and not((ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_1)) and not((ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_0))) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1) and (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_0)))) then
                right_border_buf_0_val_1_2_1_fu_142 <= right_border_buf_0_val_1_2_8_fu_877_p3;
                right_border_buf_0_val_1_2_2_fu_146 <= right_border_buf_0_val_1_2_6_fu_868_p3;
                right_border_buf_0_val_1_2_7_fu_150 <= right_border_buf_0_val_1_2_4_fu_851_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it3)))) then
                src_kernel_win_0_val_0_1_lo_reg_1511 <= src_kernel_win_0_val_0_1_fu_106;
                src_kernel_win_0_val_1_1_lo_reg_1517 <= src_kernel_win_0_val_1_1_fu_122;
                temp_0_i_i_i_057_i_i_1_1_1_reg_1523 <= temp_0_i_i_i_057_i_i_1_1_1_fu_1060_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it5) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it4)))) then
                src_kernel_win_0_val_0_2_fu_110 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it4;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it4)))) then
                src_kernel_win_0_val_0_2_lo_reg_1529 <= src_kernel_win_0_val_0_2_fu_110;
                temp_0_i_i_i_057_i_i_1_1_2_reg_1534 <= temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3;
                tmp_139_2_reg_1539 <= tmp_139_2_fu_1080_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)))) then
                src_kernel_win_0_val_1_2_fu_126 <= src_kernel_win_0_val_1_1_fu_122;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it2)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it2)))) then
                src_kernel_win_0_val_1_2_lo_reg_1496 <= src_kernel_win_0_val_1_2_fu_126;
                temp_0_i_i_i_057_i_i_1_0_2_reg_1501 <= temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3;
                tmp_139_1_reg_1506 <= tmp_139_1_fu_1033_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then
                src_kernel_win_0_val_2_2_fu_134 <= src_kernel_win_0_val_2_1_fu_118;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it1)))) then
                temp_0_i_i_i_057_i_i_1_0_1_reg_1477 <= temp_0_i_i_i_057_i_i_1_0_1_fu_910_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it5)))) then
                temp_0_i_i_i_057_i_i_1_2_1_reg_1544 <= temp_0_i_i_i_057_i_i_1_2_1_fu_1100_p3;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = tmp_19_fu_638_p2)) and not((ap_const_lv1_0 = or_cond2_fu_723_p2)))) then
                tmp_29_reg_1423 <= tmp_29_fu_729_p2;
            end if;
        end if;
    end process;
    tmp_14_cast_reg_1250(11) <= '0';
    ref_cast_reg_1267(11) <= '0';

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_sig_bdd_48, tmp_16_fu_386_p2, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_reg_ppiten_pp0_it3, ap_reg_ppiten_pp0_it4, ap_reg_ppiten_pp0_it6, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_48)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if ((tmp_16_fu_386_p2 = ap_const_lv1_0)) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
            when ap_ST_pp0_stg0_fsm_3 => 
                if ((not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it7) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it6)))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it4)))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                elsif ((((ap_const_logic_1 = ap_reg_ppiten_pp0_it7) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it6))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it3) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) and not((ap_const_logic_1 = ap_reg_ppiten_pp0_it4))))) then
                    ap_NS_fsm <= ap_ST_st12_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_3;
                end if;
            when ap_ST_st12_fsm_4 => 
                ap_NS_fsm <= ap_ST_st2_fsm_1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ImagLoc_x_fu_670_p2 <= std_logic_vector(unsigned(tmp_18_cast_fu_634_p1) + unsigned(ap_const_lv12_FFF));
    ImagLoc_y_fu_403_p2 <= std_logic_vector(unsigned(tmp_15_cast_cast_fu_382_p1) + unsigned(ap_const_lv12_FFC));

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, ap_sig_cseq_ST_st2_fsm_1, tmp_16_fu_386_p2)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_16_fu_386_p2 = ap_const_lv1_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, tmp_16_fu_386_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (tmp_16_fu_386_p2 = ap_const_lv1_0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_116 assign process. --
    ap_sig_bdd_116_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_116 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_135 assign process. --
    ap_sig_bdd_135_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_135 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    -- ap_sig_bdd_154 assign process. --
    ap_sig_bdd_154_assign_proc : process(p_src_data_stream_V_empty_n, brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)
    begin
                ap_sig_bdd_154 <= ((p_src_data_stream_V_empty_n = ap_const_logic_0) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)));
    end process;


    -- ap_sig_bdd_172 assign process. --
    ap_sig_bdd_172_assign_proc : process(p_dst_data_stream_V_full_n, ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6)
    begin
                ap_sig_bdd_172 <= ((p_dst_data_stream_V_full_n = ap_const_logic_0) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6)));
    end process;


    -- ap_sig_bdd_24 assign process. --
    ap_sig_bdd_24_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_24 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_355 assign process. --
    ap_sig_bdd_355_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_355 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    -- ap_sig_bdd_48 assign process. --
    ap_sig_bdd_48_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_48 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- ap_sig_bdd_76 assign process. --
    ap_sig_bdd_76_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_76 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_cseq_ST_pp0_stg0_fsm_3 assign process. --
    ap_sig_cseq_ST_pp0_stg0_fsm_3_assign_proc : process(ap_sig_bdd_135)
    begin
        if (ap_sig_bdd_135) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st12_fsm_4 assign process. --
    ap_sig_cseq_ST_st12_fsm_4_assign_proc : process(ap_sig_bdd_355)
    begin
        if (ap_sig_bdd_355) then 
            ap_sig_cseq_ST_st12_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st12_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_24)
    begin
        if (ap_sig_bdd_24) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_76)
    begin
        if (ap_sig_bdd_76) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st3_fsm_2 assign process. --
    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_bdd_116)
    begin
        if (ap_sig_bdd_116) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_630_p2 <= (tmp_23_reg_1296 or or_cond_reg_1301);
    col_assign_1_fu_762_p2 <= std_logic_vector(unsigned(tmp_124_fu_751_p1) + unsigned(p_neg226_i_i_cast_reg_1255));
    col_assign_fu_734_p2 <= std_logic_vector(unsigned(tmp_121_fu_680_p1) + unsigned(p_neg226_i_i_cast_reg_1255));
    col_buf_0_val_0_0_2_fu_976_p3 <= 
        col_buf_0_val_0_0_5_fu_130 when (sel_tmp_fu_971_p2(0) = '1') else 
        col_buf_0_val_0_0_3_fu_114;
    col_buf_0_val_0_0_9_fu_989_p3 <= 
        col_buf_0_val_0_0_6_fu_138 when (sel_tmp2_fu_984_p2(0) = '1') else 
        col_buf_0_val_0_0_2_fu_976_p3;
    heightloop_fu_324_p2 <= std_logic_vector(unsigned(tmp_fu_316_p1) + unsigned(ap_const_lv11_5));
    i_V_fu_391_p2 <= std_logic_vector(unsigned(p_012_0_i_i_reg_252) + unsigned(ap_const_lv11_1));
    icmp2_fu_659_p2 <= "0" when (tmp_119_fu_649_p4 = ap_const_lv10_0) else "1";
    icmp_fu_425_p2 <= "1" when (signed(tmp_106_fu_415_p4) > signed(ap_const_lv11_0)) else "0";
    j_V_fu_643_p2 <= std_logic_vector(unsigned(p_025_0_i_i_reg_263) + unsigned(ap_const_lv11_1));
    k_buf_0_val_0_address0 <= tmp_80_fu_755_p1(11 - 1 downto 0);
    k_buf_0_val_0_address1 <= k_buf_0_val_0_addr_reg_1433;

    -- k_buf_0_val_0_ce0 assign process. --
    k_buf_0_val_0_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_reg_ppiten_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
            k_buf_0_val_0_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- k_buf_0_val_0_ce1 assign process. --
    k_buf_0_val_0_ce1_assign_proc : process(ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if (((ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
            k_buf_0_val_0_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_0_d1 <= p_src_data_stream_V_dout;

    -- k_buf_0_val_0_we1 assign process. --
    k_buf_0_val_0_we1_assign_proc : process(brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7))))))) then 
            k_buf_0_val_0_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_1_address0 <= tmp_80_fu_755_p1(11 - 1 downto 0);
    k_buf_0_val_1_address1 <= k_buf_0_val_1_addr_reg_1439;

    -- k_buf_0_val_1_ce0 assign process. --
    k_buf_0_val_1_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_reg_ppiten_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
            k_buf_0_val_1_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- k_buf_0_val_1_ce1 assign process. --
    k_buf_0_val_1_ce1_assign_proc : process(brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7, ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1))))) then 
            k_buf_0_val_1_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_1_d1 <= k_buf_0_val_0_q0;

    -- k_buf_0_val_1_we1 assign process. --
    k_buf_0_val_1_we1_assign_proc : process(brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7, ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1))))) then 
            k_buf_0_val_1_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_2_address0 <= tmp_80_fu_755_p1(11 - 1 downto 0);
    k_buf_0_val_2_address1 <= k_buf_0_val_2_addr_reg_1445;

    -- k_buf_0_val_2_ce0 assign process. --
    k_buf_0_val_2_ce0_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_3, ap_reg_ppiten_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_3) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
            k_buf_0_val_2_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- k_buf_0_val_2_ce1 assign process. --
    k_buf_0_val_2_ce1_assign_proc : process(brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7, ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1))))) then 
            k_buf_0_val_2_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_2_d1 <= k_buf_0_val_1_q0;

    -- k_buf_0_val_2_we1 assign process. --
    k_buf_0_val_2_we1_assign_proc : process(brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7, ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)
    begin
        if (((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and (ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1)) or (not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))) and not((ap_const_lv1_0 = ap_reg_ppstg_tmp_29_reg_1423_pp0_it1))))) then 
            k_buf_0_val_2_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_2_we1 <= ap_const_logic_0;
        end if; 
    end process;

    locy_1_t_fu_597_p2 <= std_logic_vector(unsigned(tmp_115_reg_1337) - unsigned(tmp_81_fu_591_p3));
    locy_2_t_fu_625_p2 <= std_logic_vector(unsigned(tmp_115_reg_1337) - unsigned(tmp_83_fu_619_p3));
    locy_fu_571_p2 <= std_logic_vector(unsigned(tmp_108_reg_1310) - unsigned(tmp_111_reg_1316));
    or_cond219_i_i_fu_665_p2 <= (tmp_17_reg_1291 and icmp2_fu_659_p2);
    or_cond2_fu_723_p2 <= (tmp_26_fu_717_p2 and tmp_i_fu_698_p2);
    or_cond_fu_436_p2 <= (icmp_fu_425_p2 and tmp_25_fu_431_p2);
    or_cond_i1_fu_506_p2 <= (tmp_i1_fu_501_p2 and rev_fu_495_p2);
    or_cond_i2_fu_553_p2 <= (tmp_i2_fu_548_p2 and rev1_fu_542_p2);
    or_cond_i_fu_703_p2 <= (tmp_i_fu_698_p2 and rev2_fu_692_p2);
    p_assign_1_i_fu_745_p3 <= 
        tmp_120_reg_1400 when (or_cond_i_reg_1409(0) = '1') else 
        p_assign_fu_739_p3;
    p_assign_fu_739_p3 <= 
        ap_const_lv11_0 when (tmp_123_reg_1414(0) = '1') else 
        tmp_2_i_reg_1272;
    p_dst_data_stream_V_din <= 
        ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6 when (tmp_139_2_2_fu_1107_p2(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_2_1_reg_1544;

    -- p_dst_data_stream_V_write assign process. --
    p_dst_data_stream_V_write_assign_proc : process(ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if ((not((ap_const_lv1_0 = ap_reg_ppstg_or_cond219_i_i_reg_1396_pp0_it6)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_i_i_fu_450_p3 <= 
        ap_const_lv11_2 when (tmp_25_fu_431_p2(0) = '1') else 
        ref_reg_1261;
    p_neg226_i_i_cast_fu_350_p2 <= (tmp_104_fu_346_p1 xor ap_const_lv2_3);

    -- p_src_data_stream_V_read assign process. --
    p_src_data_stream_V_read_assign_proc : process(brmerge_reg_1383, ap_reg_ppstg_tmp_19_reg_1387_pp0_it1, ap_reg_ppstg_or_cond2_reg_1419_pp0_it1, ap_sig_bdd_154, ap_reg_ppiten_pp0_it2, ap_sig_bdd_172, ap_reg_ppiten_pp0_it7)
    begin
        if ((not((ap_const_lv1_0 = ap_reg_ppstg_tmp_19_reg_1387_pp0_it1)) and not((ap_const_lv1_0 = brmerge_reg_1383)) and not((ap_const_lv1_0 = ap_reg_ppstg_or_cond2_reg_1419_pp0_it1)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2) and not(((ap_sig_bdd_154 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it2)) or (ap_sig_bdd_172 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it7)))))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

    ref_cast_fu_362_p1 <= std_logic_vector(resize(unsigned(ref_fu_356_p2),12));
    ref_fu_356_p2 <= std_logic_vector(unsigned(tmp_fu_316_p1) + unsigned(ap_const_lv11_7FF));
    rev1_fu_542_p2 <= (tmp_116_fu_534_p3 xor ap_const_lv1_1);
    rev2_fu_692_p2 <= (tmp_122_fu_684_p3 xor ap_const_lv1_1);
    rev_fu_495_p2 <= (tmp_112_fu_487_p3 xor ap_const_lv1_1);
    right_border_buf_0_val_1_2_11_fu_1006_p3 <= 
        right_border_buf_0_val_1_2_1_fu_142 when (sel_tmp2_fu_984_p2(0) = '1') else 
        right_border_buf_0_val_1_2_fu_998_p3;
    right_border_buf_0_val_1_2_3_fu_838_p3 <= 
        right_border_buf_0_val_1_2_7_fu_150 when (sel_tmp1_fu_833_p2(0) = '1') else 
        k_buf_0_val_1_q0;
    right_border_buf_0_val_1_2_4_fu_851_p3 <= 
        right_border_buf_0_val_1_2_7_fu_150 when (sel_tmp5_fu_846_p2(0) = '1') else 
        right_border_buf_0_val_1_2_3_fu_838_p3;
    right_border_buf_0_val_1_2_5_fu_860_p3 <= 
        k_buf_0_val_1_q0 when (sel_tmp1_fu_833_p2(0) = '1') else 
        right_border_buf_0_val_1_2_2_fu_146;
    right_border_buf_0_val_1_2_6_fu_868_p3 <= 
        right_border_buf_0_val_1_2_2_fu_146 when (sel_tmp5_fu_846_p2(0) = '1') else 
        right_border_buf_0_val_1_2_5_fu_860_p3;
    right_border_buf_0_val_1_2_8_fu_877_p3 <= 
        k_buf_0_val_1_q0 when (sel_tmp5_fu_846_p2(0) = '1') else 
        right_border_buf_0_val_1_2_1_fu_142;
    right_border_buf_0_val_1_2_fu_998_p3 <= 
        right_border_buf_0_val_1_2_2_fu_146 when (sel_tmp_fu_971_p2(0) = '1') else 
        right_border_buf_0_val_1_2_7_fu_150;
    sel_tmp1_fu_833_p2 <= "1" when (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_1) else "0";
    sel_tmp2_fu_984_p2 <= "1" when (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_0) else "0";
    sel_tmp3_fu_579_p2 <= "1" when (locy_fu_571_p2 = ap_const_lv2_1) else "0";
    sel_tmp4_fu_602_p2 <= "1" when (tmp_115_reg_1337 = tmp_81_fu_591_p3) else "0";
    sel_tmp5_fu_846_p2 <= "1" when (ap_reg_ppstg_col_assign_reg_1427_pp0_it1 = ap_const_lv2_0) else "0";
    sel_tmp6_fu_941_p3 <= 
        right_border_buf_0_val_2_0_reg_1457 when (sel_tmp4_reg_1369(0) = '1') else 
        src_kernel_win_0_val_2_0_reg_1471;
    sel_tmp7_fu_607_p2 <= "1" when (locy_1_t_fu_597_p2 = ap_const_lv2_1) else "0";
    sel_tmp8_fu_575_p2 <= "1" when (tmp_108_reg_1310 = tmp_111_reg_1316) else "0";
    sel_tmp9_fu_929_p3 <= 
        right_border_buf_0_val_2_0_reg_1457 when (sel_tmp8_reg_1359(0) = '1') else 
        src_kernel_win_0_val_2_0_reg_1471;
    sel_tmp_fu_971_p2 <= "1" when (ap_reg_ppstg_col_assign_1_reg_1451_pp0_it2 = ap_const_lv2_1) else "0";
    src_kernel_win_0_val_0_0_fu_934_p3 <= 
        right_border_buf_0_val_1_0_reg_1464 when (sel_tmp3_reg_1364(0) = '1') else 
        sel_tmp9_fu_929_p3;
    src_kernel_win_0_val_1_0_fu_946_p3 <= 
        right_border_buf_0_val_1_0_reg_1464 when (sel_tmp7_reg_1374(0) = '1') else 
        sel_tmp6_fu_941_p3;
    temp_0_i_i_i_057_i_i_1_0_1_fu_910_p3 <= 
        src_kernel_win_0_val_2_1_fu_118 when (tmp_139_0_1_fu_904_p2(0) = '1') else 
        src_kernel_win_0_val_2_2_fu_134;
    temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3 <= 
        src_kernel_win_0_val_2_1_fu_118 when (tmp_139_0_2_fu_1021_p2(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_0_1_reg_1477;
    temp_0_i_i_i_057_i_i_1_1_1_fu_1060_p3 <= 
        src_kernel_win_0_val_1_1_6_reg_1490 when (tmp_139_1_1_fu_1055_p2(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_1_fu_1050_p3;
    temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3 <= 
        src_kernel_win_0_val_1_1_lo_reg_1517 when (tmp_139_1_2_fu_1070_p2(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_1_1_reg_1523;
    temp_0_i_i_i_057_i_i_1_1_fu_1050_p3 <= 
        src_kernel_win_0_val_1_2_lo_reg_1496 when (tmp_139_1_reg_1506(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_0_2_reg_1501;
    temp_0_i_i_i_057_i_i_1_2_1_fu_1100_p3 <= 
        ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5 when (tmp_139_2_1_fu_1095_p2(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_2_fu_1090_p3;
    temp_0_i_i_i_057_i_i_1_2_fu_1090_p3 <= 
        src_kernel_win_0_val_0_2_lo_reg_1529 when (tmp_139_2_reg_1539(0) = '1') else 
        temp_0_i_i_i_057_i_i_1_1_2_reg_1534;
    tmp_103_fu_320_p1 <= p_src_cols_V_read(11 - 1 downto 0);
    tmp_104_fu_346_p1 <= p_src_cols_V_read(2 - 1 downto 0);
    tmp_105_fu_372_p1 <= p_src_rows_V_read(2 - 1 downto 0);
    tmp_106_fu_415_p4 <= ImagLoc_y_fu_403_p2(11 downto 1);
    tmp_108_fu_457_p1 <= p_i_i_fu_450_p3(2 - 1 downto 0);
    tmp_109_fu_466_p1 <= ImagLoc_y_fu_403_p2(2 - 1 downto 0);
    tmp_110_fu_470_p1 <= ref_reg_1261(2 - 1 downto 0);
    tmp_111_fu_473_p3 <= 
        tmp_109_fu_466_p1 when (tmp_i5_fu_461_p2(0) = '1') else 
        tmp_110_fu_470_p1;
    tmp_112_fu_487_p3 <= y_1_fu_481_p2(11 downto 11);
    tmp_114_fu_520_p1 <= y_1_fu_481_p2(2 - 1 downto 0);
    tmp_115_fu_524_p1 <= p_i_i_fu_450_p3(2 - 1 downto 0);
    tmp_116_fu_534_p3 <= y_1_1_fu_528_p2(11 downto 11);
    tmp_118_fu_567_p1 <= y_1_1_fu_528_p2(2 - 1 downto 0);
    tmp_119_fu_649_p4 <= p_025_0_i_i_reg_263(10 downto 1);
    tmp_120_fu_676_p1 <= ImagLoc_x_fu_670_p2(11 - 1 downto 0);
    tmp_121_fu_680_p1 <= ImagLoc_x_fu_670_p2(2 - 1 downto 0);
    tmp_122_fu_684_p3 <= ImagLoc_x_fu_670_p2(11 downto 11);
    tmp_124_fu_751_p1 <= p_assign_1_i_fu_745_p3(2 - 1 downto 0);
    tmp_139_0_1_fu_904_p2 <= "1" when (unsigned(src_kernel_win_0_val_2_1_fu_118) > unsigned(src_kernel_win_0_val_2_2_fu_134)) else "0";
    tmp_139_0_2_fu_1021_p2 <= "1" when (unsigned(src_kernel_win_0_val_2_1_fu_118) > unsigned(temp_0_i_i_i_057_i_i_1_0_1_reg_1477)) else "0";
    tmp_139_1_1_fu_1055_p2 <= "1" when (unsigned(src_kernel_win_0_val_1_1_6_reg_1490) > unsigned(temp_0_i_i_i_057_i_i_1_1_fu_1050_p3)) else "0";
    tmp_139_1_2_fu_1070_p2 <= "1" when (unsigned(src_kernel_win_0_val_1_1_lo_reg_1517) > unsigned(temp_0_i_i_i_057_i_i_1_1_1_reg_1523)) else "0";
    tmp_139_1_fu_1033_p2 <= "1" when (unsigned(src_kernel_win_0_val_1_2_fu_126) > unsigned(temp_0_i_i_i_057_i_i_1_0_2_fu_1026_p3)) else "0";
    tmp_139_2_1_fu_1095_p2 <= "1" when (unsigned(ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_1483_pp0_it5) > unsigned(temp_0_i_i_i_057_i_i_1_2_fu_1090_p3)) else "0";
    tmp_139_2_2_fu_1107_p2 <= "1" when (unsigned(ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_1511_pp0_it6) > unsigned(temp_0_i_i_i_057_i_i_1_2_1_reg_1544)) else "0";
    tmp_139_2_fu_1080_p2 <= "1" when (unsigned(src_kernel_win_0_val_0_2_fu_110) > unsigned(temp_0_i_i_i_057_i_i_1_1_2_fu_1074_p3)) else "0";
    tmp_14_cast_fu_342_p1 <= std_logic_vector(resize(unsigned(tmp_14_fu_336_p2),12));
    tmp_14_fu_336_p2 <= std_logic_vector(unsigned(tmp_103_fu_320_p1) + unsigned(ap_const_lv11_7FD));
    tmp_15_cast_cast_fu_382_p1 <= std_logic_vector(resize(unsigned(p_012_0_i_i_reg_252),12));
    tmp_16_fu_386_p2 <= "1" when (unsigned(p_012_0_i_i_reg_252) < unsigned(heightloop_reg_1240)) else "0";
    tmp_17_fu_397_p2 <= "1" when (unsigned(p_012_0_i_i_reg_252) > unsigned(ap_const_lv11_4)) else "0";
    tmp_18_cast_fu_634_p1 <= std_logic_vector(resize(unsigned(p_025_0_i_i_reg_263),12));
    tmp_19_fu_638_p2 <= "1" when (unsigned(p_025_0_i_i_reg_263) < unsigned(widthloop_reg_1245)) else "0";
    tmp_23_fu_409_p2 <= "1" when (signed(ImagLoc_y_fu_403_p2) < signed(ap_const_lv12_FFF)) else "0";
    tmp_25_fu_431_p2 <= "1" when (signed(ImagLoc_y_fu_403_p2) < signed(ref_cast_reg_1267)) else "0";
    tmp_26_fu_717_p2 <= "0" when (p_025_0_i_i_reg_263 = ap_const_lv11_0) else "1";
    tmp_29_fu_729_p2 <= "1" when (signed(ImagLoc_x_fu_670_p2) < signed(tmp_14_cast_reg_1250)) else "0";
    tmp_2_i1_fu_376_p2 <= std_logic_vector(unsigned(tmp_105_fu_372_p1) + unsigned(ap_const_lv2_3));
    tmp_2_i_fu_366_p2 <= std_logic_vector(unsigned(tmp_103_fu_320_p1) + unsigned(ap_const_lv11_7FF));
    tmp_80_fu_755_p1 <= std_logic_vector(resize(unsigned(p_assign_1_i_fu_745_p3),64));
    tmp_81_fu_591_p3 <= 
        tmp_114_reg_1332 when (or_cond_i1_reg_1322(0) = '1') else 
        tmp_s_fu_585_p3;
    tmp_82_fu_613_p3 <= 
        ap_const_lv2_0 when (tmp_117_reg_1349(0) = '1') else 
        tmp_2_i1_reg_1277;
    tmp_83_fu_619_p3 <= 
        tmp_118_reg_1354 when (or_cond_i2_reg_1344(0) = '1') else 
        tmp_82_fu_613_p3;
    tmp_fu_316_p1 <= p_src_rows_V_read(11 - 1 downto 0);
    tmp_i1_fu_501_p2 <= "1" when (signed(y_1_fu_481_p2) < signed(p_src_rows_V_read)) else "0";
    tmp_i2_fu_548_p2 <= "1" when (signed(y_1_1_fu_528_p2) < signed(p_src_rows_V_read)) else "0";
    tmp_i5_fu_461_p2 <= "1" when (signed(ImagLoc_y_fu_403_p2) < signed(p_src_rows_V_read)) else "0";
    tmp_i_fu_698_p2 <= "1" when (signed(ImagLoc_x_fu_670_p2) < signed(p_src_cols_V_read)) else "0";
    tmp_s_fu_585_p3 <= 
        ap_const_lv2_0 when (tmp_113_reg_1327(0) = '1') else 
        tmp_2_i1_reg_1277;
    widthloop_fu_330_p2 <= std_logic_vector(unsigned(tmp_103_fu_320_p1) + unsigned(ap_const_lv11_2));
    y_1_1_fu_528_p2 <= std_logic_vector(unsigned(tmp_15_cast_cast_fu_382_p1) + unsigned(ap_const_lv12_FFA));
    y_1_fu_481_p2 <= std_logic_vector(unsigned(tmp_15_cast_cast_fu_382_p1) + unsigned(ap_const_lv12_FFB));
end behav;
