-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter_UVdownsampling is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    yuv444_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    yuv444_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
    yuv444_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    yuv444_data_stream_0_V_empty_n : IN STD_LOGIC;
    yuv444_data_stream_0_V_read : OUT STD_LOGIC;
    yuv444_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    yuv444_data_stream_1_V_empty_n : IN STD_LOGIC;
    yuv444_data_stream_1_V_read : OUT STD_LOGIC;
    yuv444_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    yuv444_data_stream_2_V_empty_n : IN STD_LOGIC;
    yuv444_data_stream_2_V_read : OUT STD_LOGIC;
    yuv422_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    yuv422_data_stream_0_V_full_n : IN STD_LOGIC;
    yuv422_data_stream_0_V_write : OUT STD_LOGIC;
    yuv422_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    yuv422_data_stream_1_V_full_n : IN STD_LOGIC;
    yuv422_data_stream_1_V_write : OUT STD_LOGIC );
end;


architecture behav of image_filter_UVdownsampling is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_pp0_stg0_fsm_2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_pp0_stg1_fsm_3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_23 : BOOLEAN;
    signal p_2_reg_127 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_bdd_59 : BOOLEAN;
    signal exitcond_fu_139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_71 : BOOLEAN;
    signal i_V_fu_144_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_V_reg_175 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_180 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_pp0_stg0_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_82 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it0 : STD_LOGIC := '0';
    signal ap_sig_bdd_103 : BOOLEAN;
    signal ap_reg_ppiten_pp0_it1 : STD_LOGIC := '0';
    signal j_V_fu_155_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal j_V_reg_184 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_132_reg_189 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_pp0_stg1_fsm_3 : STD_LOGIC;
    signal ap_sig_bdd_123 : BOOLEAN;
    signal p_s_reg_116 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_2_phi_fu_131_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_bdd_146 : BOOLEAN;
    signal ap_sig_bdd_140 : BOOLEAN;


begin




    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- ap_done_reg assign process. --
    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((exitcond_fu_139_p2 = ap_const_lv1_0)))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it0 assign process. --
    ap_reg_ppiten_pp0_it0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (tmp_fu_150_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_139_p2 = ap_const_lv1_0))) then 
                    ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ppiten_pp0_it1 assign process. --
    ap_reg_ppiten_pp0_it1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
            else
                if ((not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103)))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
                elsif ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_139_p2 = ap_const_lv1_0)) or ((tmp_reg_180 = ap_const_lv1_0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))))) then 
                    ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    -- p_2_reg_127 assign process. --
    p_2_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and (exitcond_fu_139_p2 = ap_const_lv1_0))) then 
                p_2_reg_127 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then 
                p_2_reg_127 <= j_V_reg_184;
            end if; 
        end if;
    end process;

    -- p_s_reg_116 assign process. --
    p_s_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (tmp_fu_150_p2 = ap_const_lv1_0))) then 
                p_s_reg_116 <= i_V_reg_175;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not(ap_sig_bdd_59))) then 
                p_s_reg_116 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                i_V_reg_175 <= i_V_fu_144_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not((tmp_fu_150_p2 = ap_const_lv1_0)))) then
                j_V_reg_184 <= j_V_fu_155_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103)))) then
                tmp_132_reg_189 <= yuv444_data_stream_2_V_dout;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))))) then
                tmp_reg_180 <= tmp_fu_150_p2;
            end if;
        end if;
    end process;

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_sig_bdd_59, exitcond_fu_139_p2, tmp_fu_150_p2, ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not(ap_sig_bdd_59)) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((exitcond_fu_139_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_pp0_stg0_fsm_2 => 
                if ((not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (tmp_fu_150_p2 = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_pp0_stg1_fsm_3;
                elsif (((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) and (tmp_fu_150_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                end if;
            when ap_ST_pp0_stg1_fsm_3 => 
                if (not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))) then
                    ap_NS_fsm <= ap_ST_pp0_stg0_fsm_2;
                else
                    ap_NS_fsm <= ap_ST_pp0_stg1_fsm_3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_done_reg, exitcond_fu_139_p2, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_done_reg) or ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((exitcond_fu_139_p2 = ap_const_lv1_0))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(exitcond_fu_139_p2, ap_sig_cseq_ST_st2_fsm_1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((exitcond_fu_139_p2 = ap_const_lv1_0)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_103 assign process. --
    ap_sig_bdd_103_assign_proc : process(yuv444_data_stream_0_V_empty_n, yuv444_data_stream_1_V_empty_n, yuv444_data_stream_2_V_empty_n, yuv422_data_stream_0_V_full_n, yuv422_data_stream_1_V_full_n, tmp_reg_180)
    begin
                ap_sig_bdd_103 <= (((yuv444_data_stream_0_V_empty_n = ap_const_logic_0) and not((tmp_reg_180 = ap_const_lv1_0))) or (not((tmp_reg_180 = ap_const_lv1_0)) and (yuv444_data_stream_1_V_empty_n = ap_const_logic_0)) or (not((tmp_reg_180 = ap_const_lv1_0)) and (yuv444_data_stream_2_V_empty_n = ap_const_logic_0)) or (not((tmp_reg_180 = ap_const_lv1_0)) and (yuv422_data_stream_0_V_full_n = ap_const_logic_0)) or (not((tmp_reg_180 = ap_const_lv1_0)) and (yuv422_data_stream_1_V_full_n = ap_const_logic_0)));
    end process;


    -- ap_sig_bdd_123 assign process. --
    ap_sig_bdd_123_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_123 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    -- ap_sig_bdd_140 assign process. --
    ap_sig_bdd_140_assign_proc : process(ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1)
    begin
                ap_sig_bdd_140 <= ((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))));
    end process;


    -- ap_sig_bdd_146 assign process. --
    ap_sig_bdd_146_assign_proc : process(ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_sig_cseq_ST_pp0_stg1_fsm_3)
    begin
                ap_sig_bdd_146 <= ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103)));
    end process;


    -- ap_sig_bdd_23 assign process. --
    ap_sig_bdd_23_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_23 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_59 assign process. --
    ap_sig_bdd_59_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_sig_bdd_59 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    -- ap_sig_bdd_71 assign process. --
    ap_sig_bdd_71_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_71 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_82 assign process. --
    ap_sig_bdd_82_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_82 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_cseq_ST_pp0_stg0_fsm_2 assign process. --
    ap_sig_cseq_ST_pp0_stg0_fsm_2_assign_proc : process(ap_sig_bdd_82)
    begin
        if (ap_sig_bdd_82) then 
            ap_sig_cseq_ST_pp0_stg0_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg0_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_pp0_stg1_fsm_3 assign process. --
    ap_sig_cseq_ST_pp0_stg1_fsm_3_assign_proc : process(ap_sig_bdd_123)
    begin
        if (ap_sig_bdd_123) then 
            ap_sig_cseq_ST_pp0_stg1_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_pp0_stg1_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_23)
    begin
        if (ap_sig_bdd_23) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_71)
    begin
        if (ap_sig_bdd_71) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_fu_139_p2 <= "1" when (p_s_reg_116 = yuv444_rows_V_read) else "0";
    i_V_fu_144_p2 <= std_logic_vector(unsigned(p_s_reg_116) + unsigned(ap_const_lv12_1));
    j_V_fu_155_p2 <= std_logic_vector(unsigned(p_2_phi_fu_131_p4) + unsigned(ap_const_lv12_2));

    -- p_2_phi_fu_131_p4 assign process. --
    p_2_phi_fu_131_p4_assign_proc : process(p_2_reg_127, tmp_reg_180, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it1, j_V_reg_184)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1))) then 
            p_2_phi_fu_131_p4 <= j_V_reg_184;
        else 
            p_2_phi_fu_131_p4 <= p_2_reg_127;
        end if; 
    end process;

    tmp_fu_150_p2 <= "1" when (unsigned(p_2_phi_fu_131_p4) < unsigned(yuv444_cols_V_read)) else "0";
    yuv422_data_stream_0_V_din <= yuv444_data_stream_0_V_dout;

    -- yuv422_data_stream_0_V_write assign process. --
    yuv422_data_stream_0_V_write_assign_proc : process(tmp_reg_180, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg1_fsm_3)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))))) then 
            yuv422_data_stream_0_V_write <= ap_const_logic_1;
        else 
            yuv422_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    -- yuv422_data_stream_1_V_din assign process. --
    yuv422_data_stream_1_V_din_assign_proc : process(yuv444_data_stream_1_V_dout, tmp_reg_180, tmp_132_reg_189, ap_sig_bdd_146, ap_sig_bdd_140)
    begin
        if (not((tmp_reg_180 = ap_const_lv1_0))) then
            if (ap_sig_bdd_140) then 
                yuv422_data_stream_1_V_din <= tmp_132_reg_189;
            elsif (ap_sig_bdd_146) then 
                yuv422_data_stream_1_V_din <= yuv444_data_stream_1_V_dout;
            else 
                yuv422_data_stream_1_V_din <= "XXXXXXXX";
            end if;
        else 
            yuv422_data_stream_1_V_din <= "XXXXXXXX";
        end if; 
    end process;


    -- yuv422_data_stream_1_V_write assign process. --
    yuv422_data_stream_1_V_write_assign_proc : process(tmp_reg_180, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg1_fsm_3)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))))) then 
            yuv422_data_stream_1_V_write <= ap_const_logic_1;
        else 
            yuv422_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    -- yuv444_data_stream_0_V_read assign process. --
    yuv444_data_stream_0_V_read_assign_proc : process(tmp_reg_180, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg1_fsm_3)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))))) then 
            yuv444_data_stream_0_V_read <= ap_const_logic_1;
        else 
            yuv444_data_stream_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- yuv444_data_stream_1_V_read assign process. --
    yuv444_data_stream_1_V_read_assign_proc : process(tmp_reg_180, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg1_fsm_3)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))))) then 
            yuv444_data_stream_1_V_read <= ap_const_logic_1;
        else 
            yuv444_data_stream_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    -- yuv444_data_stream_2_V_read assign process. --
    yuv444_data_stream_2_V_read_assign_proc : process(tmp_reg_180, ap_sig_cseq_ST_pp0_stg0_fsm_2, ap_reg_ppiten_pp0_it0, ap_sig_bdd_103, ap_reg_ppiten_pp0_it1, ap_sig_cseq_ST_pp0_stg1_fsm_3)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg0_fsm_2) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1) and not((ap_sig_bdd_103 and (ap_const_logic_1 = ap_reg_ppiten_pp0_it1)))) or ((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and not((tmp_reg_180 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_sig_cseq_ST_pp0_stg1_fsm_3) and not(((ap_const_logic_1 = ap_reg_ppiten_pp0_it0) and ap_sig_bdd_103))))) then 
            yuv444_data_stream_2_V_read <= ap_const_logic_1;
        else 
            yuv444_data_stream_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

end behav;
