/* Definition for CPU ID */
#define XPAR_CPU_ID 0

/* Definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_PS7_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

/* Canonical definitions for peripheral PS7_CORTEXA9_0 */
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ 666666687


/******************************************************************/

#include "xparameters_ps.h"

#define STDIN_BASEADDRESS 0xE0001000
#define STDOUT_BASEADDRESS 0xE0001000

/******************************************************************/

/* Definitions for driver AXIPMON */
#define XPAR_XAXIPMON_NUM_INSTANCES 1

/* Definitions for peripheral AXI_PERF_MON_1 */
#define XPAR_AXI_PERF_MON_1_DEVICE_ID 0
#define XPAR_AXI_PERF_MON_1_BASEADDR 0x400F0000
#define XPAR_AXI_PERF_MON_1_HIGHADDR 0x400FFFFF
#define XPAR_AXI_PERF_MON_1_GLOBAL_COUNT_WIDTH 32
#define XPAR_AXI_PERF_MON_1_METRICS_SAMPLE_COUNT_WIDTH 32
#define XPAR_AXI_PERF_MON_1_ENABLE_EVENT_COUNT 0
#define XPAR_AXI_PERF_MON_1_NUM_MONITOR_SLOTS 3
#define XPAR_AXI_PERF_MON_1_NUM_OF_COUNTERS 4
#define XPAR_AXI_PERF_MON_1_HAVE_SAMPLED_METRIC_CNT 1
#define XPAR_AXI_PERF_MON_1_ENABLE_EVENT_LOG 0
#define XPAR_AXI_PERF_MON_1_FIFO_AXIS_DEPTH 32
#define XPAR_AXI_PERF_MON_1_FIFO_AXIS_TDATA_WIDTH 56
#define XPAR_AXI_PERF_MON_1_FIFO_AXIS_TID_WIDTH 1
#define XPAR_AXI_PERF_MON_1_METRIC_COUNT_SCALE 1
#define XPAR_AXI_PERF_MON_1_ENABLE_ADVANCED 0
#define XPAR_AXI_PERF_MON_1_ENABLE_PROFILE 1
#define XPAR_AXI_PERF_MON_1_ENABLE_TRACE 0
#define XPAR_AXI_PERF_MON_1_S_AXI4_BASEADDR 0xFFFFFFFF
#define XPAR_AXI_PERF_MON_1_S_AXI4_HIGHADDR 0x00000000


/******************************************************************/

/* Canonical definitions for peripheral AXI_PERF_MON_1 */
#define XPAR_AXIPMON_0_DEVICE_ID XPAR_AXI_PERF_MON_1_DEVICE_ID
#define XPAR_AXIPMON_0_BASEADDR 0x400F0000
#define XPAR_AXIPMON_0_HIGHADDR 0x400FFFFF
#define XPAR_AXIPMON_0_GLOBAL_COUNT_WIDTH 32
#define XPAR_AXIPMON_0_METRICS_SAMPLE_COUNT_WIDTH 32
#define XPAR_AXIPMON_0_ENABLE_EVENT_COUNT 0
#define XPAR_AXIPMON_0_NUM_MONITOR_SLOTS 3
#define XPAR_AXIPMON_0_NUM_OF_COUNTERS 4
#define XPAR_AXIPMON_0_HAVE_SAMPLED_METRIC_CNT 1
#define XPAR_AXIPMON_0_ENABLE_EVENT_LOG 0
#define XPAR_AXIPMON_0_FIFO_AXIS_DEPTH 32
#define XPAR_AXIPMON_0_FIFO_AXIS_TDATA_WIDTH 56
#define XPAR_AXIPMON_0_FIFO_AXIS_TID_WIDTH 1
#define XPAR_AXIPMON_0_METRIC_COUNT_SCALE 1
#define XPAR_AXIPMON_0_ENABLE_ADVANCED 0
#define XPAR_AXIPMON_0_ENABLE_PROFILE 1
#define XPAR_AXIPMON_0_ENABLE_TRACE 0
#define XPAR_AXIPMON_0_S_AXI4_BASEADDR 0xFFFFFFFF
#define XPAR_AXIPMON_0_S_AXI4_HIGHADDR 0x00000000


/******************************************************************/

/* Definitions for driver AXIVDMA */
#define XPAR_XAXIVDMA_NUM_INSTANCES 2

/* Definitions for peripheral FMC_HDMI_INPUT_AXI_VDMA_1 */
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_DEVICE_ID 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_BASEADDR 0x40090000
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_HIGHADDR 0x4009FFFF
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_NUM_FSTORES 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_INCLUDE_MM2S 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_INCLUDE_MM2S_DRE 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_M_AXI_MM2S_DATA_WIDTH 64
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_INCLUDE_S2MM 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_INCLUDE_S2MM_DRE 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_AXI_MM2S_ACLK_FREQ_HZ 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_AXI_S2MM_ACLK_FREQ_HZ 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_MM2S_GENLOCK_MODE 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_MM2S_GENLOCK_NUM_MASTERS 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_S2MM_GENLOCK_MODE 2
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_S2MM_GENLOCK_NUM_MASTERS 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_INCLUDE_SG 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_VIDPRMTR_READS 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_USE_FSYNC 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_FLUSH_ON_FSYNC 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_MM2S_LINEBUFFER_DEPTH 512
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_S2MM_LINEBUFFER_DEPTH 4096
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_INCLUDE_INTERNAL_GENLOCK 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_S2MM_SOF_ENABLE 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_M_AXIS_MM2S_TDATA_WIDTH 32
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_S_AXIS_S2MM_TDATA_WIDTH 16
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_1 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_5 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_6 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_7 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_9 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_13 0
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_14 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_INFO_15 1
#define XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_ENABLE_DEBUG_ALL 0


/* Definitions for peripheral PROCESSING_AXI_VDMA_2 */
#define XPAR_PROCESSING_AXI_VDMA_2_DEVICE_ID 1
#define XPAR_PROCESSING_AXI_VDMA_2_BASEADDR 0x400B0000
#define XPAR_PROCESSING_AXI_VDMA_2_HIGHADDR 0x400BFFFF
#define XPAR_PROCESSING_AXI_VDMA_2_NUM_FSTORES 1
#define XPAR_PROCESSING_AXI_VDMA_2_INCLUDE_MM2S 1
#define XPAR_PROCESSING_AXI_VDMA_2_INCLUDE_MM2S_DRE 0
#define XPAR_PROCESSING_AXI_VDMA_2_M_AXI_MM2S_DATA_WIDTH 32
#define XPAR_PROCESSING_AXI_VDMA_2_INCLUDE_S2MM 1
#define XPAR_PROCESSING_AXI_VDMA_2_INCLUDE_S2MM_DRE 0
#define XPAR_PROCESSING_AXI_VDMA_2_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_PROCESSING_AXI_VDMA_2_AXI_MM2S_ACLK_FREQ_HZ 0
#define XPAR_PROCESSING_AXI_VDMA_2_AXI_S2MM_ACLK_FREQ_HZ 0
#define XPAR_PROCESSING_AXI_VDMA_2_MM2S_GENLOCK_MODE 3
#define XPAR_PROCESSING_AXI_VDMA_2_MM2S_GENLOCK_NUM_MASTERS 1
#define XPAR_PROCESSING_AXI_VDMA_2_S2MM_GENLOCK_MODE 2
#define XPAR_PROCESSING_AXI_VDMA_2_S2MM_GENLOCK_NUM_MASTERS 1
#define XPAR_PROCESSING_AXI_VDMA_2_INCLUDE_SG 0
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_VIDPRMTR_READS 1
#define XPAR_PROCESSING_AXI_VDMA_2_USE_FSYNC 1
#define XPAR_PROCESSING_AXI_VDMA_2_FLUSH_ON_FSYNC 1
#define XPAR_PROCESSING_AXI_VDMA_2_MM2S_LINEBUFFER_DEPTH 4096
#define XPAR_PROCESSING_AXI_VDMA_2_S2MM_LINEBUFFER_DEPTH 4096
#define XPAR_PROCESSING_AXI_VDMA_2_INCLUDE_INTERNAL_GENLOCK 1
#define XPAR_PROCESSING_AXI_VDMA_2_S2MM_SOF_ENABLE 1
#define XPAR_PROCESSING_AXI_VDMA_2_M_AXIS_MM2S_TDATA_WIDTH 16
#define XPAR_PROCESSING_AXI_VDMA_2_S_AXIS_S2MM_TDATA_WIDTH 16
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_1 0
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_5 0
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_6 1
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_7 1
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_9 0
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_13 0
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_14 1
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_INFO_15 1
#define XPAR_PROCESSING_AXI_VDMA_2_ENABLE_DEBUG_ALL 0


/******************************************************************/

/* Canonical definitions for peripheral FMC_HDMI_INPUT_AXI_VDMA_1 */
#define XPAR_AXIVDMA_0_DEVICE_ID XPAR_FMC_HDMI_INPUT_AXI_VDMA_1_DEVICE_ID
#define XPAR_AXIVDMA_0_BASEADDR 0x40090000
#define XPAR_AXIVDMA_0_HIGHADDR 0x4009FFFF
#define XPAR_AXIVDMA_0_NUM_FSTORES 1
#define XPAR_AXIVDMA_0_INCLUDE_MM2S 0
#define XPAR_AXIVDMA_0_INCLUDE_MM2S_DRE 0
#define XPAR_AXIVDMA_0_M_AXI_MM2S_DATA_WIDTH 64
#define XPAR_AXIVDMA_0_INCLUDE_S2MM 1
#define XPAR_AXIVDMA_0_INCLUDE_S2MM_DRE 0
#define XPAR_AXIVDMA_0_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXIVDMA_0_AXI_MM2S_ACLK_FREQ_HZ 0
#define XPAR_AXIVDMA_0_AXI_S2MM_ACLK_FREQ_HZ 0
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_MODE 0
#define XPAR_AXIVDMA_0_MM2S_GENLOCK_NUM_MASTERS 1
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_MODE 2
#define XPAR_AXIVDMA_0_S2MM_GENLOCK_NUM_MASTERS 1
#define XPAR_AXIVDMA_0_INCLUDE_SG 0
#define XPAR_AXIVDMA_0_ENABLE_VIDPRMTR_READS 1
#define XPAR_AXIVDMA_0_USE_FSYNC 1
#define XPAR_AXIVDMA_0_FLUSH_ON_FSYNC 1
#define XPAR_AXIVDMA_0_MM2S_LINEBUFFER_DEPTH 512
#define XPAR_AXIVDMA_0_S2MM_LINEBUFFER_DEPTH 4096
#define XPAR_AXIVDMA_0_INCLUDE_INTERNAL_GENLOCK 1
#define XPAR_AXIVDMA_0_S2MM_SOF_ENABLE 1
#define XPAR_AXIVDMA_0_M_AXIS_MM2S_TDATA_WIDTH 32
#define XPAR_AXIVDMA_0_S_AXIS_S2MM_TDATA_WIDTH 16
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_1 0
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_5 0
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_6 1
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_7 1
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_9 0
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_13 0
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_14 1
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_INFO_15 1
#define XPAR_AXIVDMA_0_ENABLE_DEBUG_ALL 0

/* Canonical definitions for peripheral PROCESSING_AXI_VDMA_2 */
#define XPAR_AXIVDMA_1_DEVICE_ID XPAR_PROCESSING_AXI_VDMA_2_DEVICE_ID
#define XPAR_AXIVDMA_1_BASEADDR 0x400B0000
#define XPAR_AXIVDMA_1_HIGHADDR 0x400BFFFF
#define XPAR_AXIVDMA_1_NUM_FSTORES 1
#define XPAR_AXIVDMA_1_INCLUDE_MM2S 1
#define XPAR_AXIVDMA_1_INCLUDE_MM2S_DRE 0
#define XPAR_AXIVDMA_1_M_AXI_MM2S_DATA_WIDTH 32
#define XPAR_AXIVDMA_1_INCLUDE_S2MM 1
#define XPAR_AXIVDMA_1_INCLUDE_S2MM_DRE 0
#define XPAR_AXIVDMA_1_M_AXI_S2MM_DATA_WIDTH 32
#define XPAR_AXIVDMA_1_AXI_MM2S_ACLK_FREQ_HZ 0
#define XPAR_AXIVDMA_1_AXI_S2MM_ACLK_FREQ_HZ 0
#define XPAR_AXIVDMA_1_MM2S_GENLOCK_MODE 3
#define XPAR_AXIVDMA_1_MM2S_GENLOCK_NUM_MASTERS 1
#define XPAR_AXIVDMA_1_S2MM_GENLOCK_MODE 2
#define XPAR_AXIVDMA_1_S2MM_GENLOCK_NUM_MASTERS 1
#define XPAR_AXIVDMA_1_INCLUDE_SG 0
#define XPAR_AXIVDMA_1_ENABLE_VIDPRMTR_READS 1
#define XPAR_AXIVDMA_1_USE_FSYNC 1
#define XPAR_AXIVDMA_1_FLUSH_ON_FSYNC 1
#define XPAR_AXIVDMA_1_MM2S_LINEBUFFER_DEPTH 4096
#define XPAR_AXIVDMA_1_S2MM_LINEBUFFER_DEPTH 4096
#define XPAR_AXIVDMA_1_INCLUDE_INTERNAL_GENLOCK 1
#define XPAR_AXIVDMA_1_S2MM_SOF_ENABLE 1
#define XPAR_AXIVDMA_1_M_AXIS_MM2S_TDATA_WIDTH 16
#define XPAR_AXIVDMA_1_S_AXIS_S2MM_TDATA_WIDTH 16
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_1 0
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_5 0
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_6 1
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_7 1
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_9 0
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_13 0
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_14 1
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_INFO_15 1
#define XPAR_AXIVDMA_1_ENABLE_DEBUG_ALL 0


/******************************************************************/

/* Definitions for driver DEVCFG */
#define XPAR_XDCFG_NUM_INSTANCES 1

/* Definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_PS7_DEV_CFG_0_DEVICE_ID 0
#define XPAR_PS7_DEV_CFG_0_BASEADDR 0xF8007000
#define XPAR_PS7_DEV_CFG_0_HIGHADDR 0xF80070FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DEV_CFG_0 */
#define XPAR_XDCFG_0_DEVICE_ID XPAR_PS7_DEV_CFG_0_DEVICE_ID
#define XPAR_XDCFG_0_BASEADDR 0xF8007000
#define XPAR_XDCFG_0_HIGHADDR 0xF80070FF


/******************************************************************/

/* Definitions for driver DMAPS */
#define XPAR_XDMAPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_DEVICE_ID 0
#define XPAR_PS7_DMA_NS_BASEADDR 0xF8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xF8004FFF


/* Definitions for peripheral PS7_DMA_S */
#define XPAR_PS7_DMA_S_DEVICE_ID 1
#define XPAR_PS7_DMA_S_BASEADDR 0xF8003000
#define XPAR_PS7_DMA_S_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_XDMAPS_0_DEVICE_ID XPAR_PS7_DMA_NS_DEVICE_ID
#define XPAR_XDMAPS_0_BASEADDR 0xF8004000
#define XPAR_XDMAPS_0_HIGHADDR 0xF8004FFF

/* Canonical definitions for peripheral PS7_DMA_S */
#define XPAR_XDMAPS_1_DEVICE_ID XPAR_PS7_DMA_S_DEVICE_ID
#define XPAR_XDMAPS_1_BASEADDR 0xF8003000
#define XPAR_XDMAPS_1_HIGHADDR 0xF8003FFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_PS7_ETHERNET_0_DEVICE_ID 0
#define XPAR_PS7_ETHERNET_0_BASEADDR 0xE000B000
#define XPAR_PS7_ETHERNET_0_HIGHADDR 0xE000BFFF
#define XPAR_PS7_ETHERNET_0_ENET_CLK_FREQ_HZ 25000000
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 5
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 8
#define XPAR_PS7_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 50


/******************************************************************/

/* Canonical definitions for peripheral PS7_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PS7_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xE000B000
#define XPAR_XEMACPS_0_HIGHADDR 0xE000BFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 25000000
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 5
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 8
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 50


/******************************************************************/


/* Definitions for peripheral HDMI_OUTPUT_LOGICVC_1 */
#define XPAR_HDMI_OUTPUT_LOGICVC_1_REGS_BASEADDR 0x40030000
#define XPAR_HDMI_OUTPUT_LOGICVC_1_REGS_HIGHADDR 0x4003FFFF


/* Definitions for peripheral PROCESSING_IMAGE_FILTER_1 */
#define XPAR_PROCESSING_IMAGE_FILTER_1_S_AXI_CONTROL_BUS_BASEADDR 0x400D0000
#define XPAR_PROCESSING_IMAGE_FILTER_1_S_AXI_CONTROL_BUS_HIGHADDR 0x400DFFFF


/* Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_S_AXI_BASEADDR 0xF8008000
#define XPAR_PS7_AFI_0_S_AXI_HIGHADDR 0xF8008FFF


/* Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_S_AXI_BASEADDR 0xF8009000
#define XPAR_PS7_AFI_1_S_AXI_HIGHADDR 0xF8009FFF


/* Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_S_AXI_BASEADDR 0xF800A000
#define XPAR_PS7_AFI_2_S_AXI_HIGHADDR 0xF800AFFF


/* Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_S_AXI_BASEADDR 0xF800B000
#define XPAR_PS7_AFI_3_S_AXI_HIGHADDR 0xF800BFFF


/* Definitions for peripheral PS7_CORESIGHT_COMP_0 */
#define XPAR_PS7_CORESIGHT_COMP_0_S_AXI_BASEADDR 0xF8800000
#define XPAR_PS7_CORESIGHT_COMP_0_S_AXI_HIGHADDR 0xF88FFFFF


/* Definitions for peripheral PS7_DDR_0 */
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR 0x00100000
#define XPAR_PS7_DDR_0_S_AXI_HIGHADDR 0x3FFFFFFF


/* Definitions for peripheral PS7_DDRC_0 */
#define XPAR_PS7_DDRC_0_S_AXI_BASEADDR 0xF8006000
#define XPAR_PS7_DDRC_0_S_AXI_HIGHADDR 0xF8006FFF


/* Definitions for peripheral PS7_GLOBALTIMER_0 */
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_BASEADDR 0xF8F00200
#define XPAR_PS7_GLOBALTIMER_0_S_AXI_HIGHADDR 0xF8F002FF


/* Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_S_AXI_BASEADDR 0xF8900000
#define XPAR_PS7_GPV_0_S_AXI_HIGHADDR 0xF89FFFFF


/* Definitions for peripheral PS7_INTC_DIST_0 */
#define XPAR_PS7_INTC_DIST_0_S_AXI_BASEADDR 0xF8F01000
#define XPAR_PS7_INTC_DIST_0_S_AXI_HIGHADDR 0xF8F01FFF


/* Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_BASEADDR 0xE0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_S_AXI_HIGHADDR 0xE0200FFF


/* Definitions for peripheral PS7_L2CACHEC_0 */
#define XPAR_PS7_L2CACHEC_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_L2CACHEC_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_S_AXI_BASEADDR 0xF800C000
#define XPAR_PS7_OCMC_0_S_AXI_HIGHADDR 0xF800CFFF


/* Definitions for peripheral PS7_PL310_0 */
#define XPAR_PS7_PL310_0_S_AXI_BASEADDR 0xF8F02000
#define XPAR_PS7_PL310_0_S_AXI_HIGHADDR 0xF8F02FFF


/* Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_S_AXI_BASEADDR 0xF8891000
#define XPAR_PS7_PMU_0_S_AXI_HIGHADDR 0xF8891FFF
#define XPAR_PS7_PMU_0_PMU1_S_AXI_BASEADDR 0xF8893000
#define XPAR_PS7_PMU_0_PMU1_S_AXI_HIGHADDR 0xF8893FFF


/* Definitions for peripheral PS7_QSPI_LINEAR_0 */
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR 0xFC000000
#define XPAR_PS7_QSPI_LINEAR_0_S_AXI_HIGHADDR 0xFCFFFFFF


/* Definitions for peripheral PS7_RAM_0 */
#define XPAR_PS7_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PS7_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Definitions for peripheral PS7_RAM_1 */
#define XPAR_PS7_RAM_1_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PS7_RAM_1_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_S_AXI_BASEADDR 0xF8F00000
#define XPAR_PS7_SCUC_0_S_AXI_HIGHADDR 0xF8F000FC


/* Definitions for peripheral PS7_SLCR_0 */
#define XPAR_PS7_SLCR_0_S_AXI_BASEADDR 0xF8000000
#define XPAR_PS7_SLCR_0_S_AXI_HIGHADDR 0xF8000FFF


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_GPIO_0 */
#define XPAR_PS7_GPIO_0_DEVICE_ID 0
#define XPAR_PS7_GPIO_0_BASEADDR 0xE000A000
#define XPAR_PS7_GPIO_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_GPIO_0 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PS7_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xE000A000
#define XPAR_XGPIOPS_0_HIGHADDR 0xE000AFFF


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 2

/* Definitions for peripheral PS7_I2C_0 */
#define XPAR_PS7_I2C_0_DEVICE_ID 0
#define XPAR_PS7_I2C_0_BASEADDR 0xE0004000
#define XPAR_PS7_I2C_0_HIGHADDR 0xE0004FFF
#define XPAR_PS7_I2C_0_I2C_CLK_FREQ_HZ 111111115


/* Definitions for peripheral PS7_I2C_1 */
#define XPAR_PS7_I2C_1_DEVICE_ID 1
#define XPAR_PS7_I2C_1_BASEADDR 0xE0005000
#define XPAR_PS7_I2C_1_HIGHADDR 0xE0005FFF
#define XPAR_PS7_I2C_1_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Canonical definitions for peripheral PS7_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PS7_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xE0004000
#define XPAR_XIICPS_0_HIGHADDR 0xE0004FFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 111111115

/* Canonical definitions for peripheral PS7_I2C_1 */
#define XPAR_XIICPS_1_DEVICE_ID XPAR_PS7_I2C_1_DEVICE_ID
#define XPAR_XIICPS_1_BASEADDR 0xE0005000
#define XPAR_XIICPS_1_HIGHADDR 0xE0005FFF
#define XPAR_XIICPS_1_I2C_CLK_FREQ_HZ 111111115


/******************************************************************/

/* Definitions for driver QSPIPS */
#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_QSPI_0 */
#define XPAR_PS7_QSPI_0_DEVICE_ID 0
#define XPAR_PS7_QSPI_0_BASEADDR 0xE000D000
#define XPAR_PS7_QSPI_0_HIGHADDR 0xE000DFFF
#define XPAR_PS7_QSPI_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_PS7_QSPI_0_QSPI_MODE 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_QSPI_0 */
#define XPAR_XQSPIPS_0_DEVICE_ID XPAR_PS7_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPS_0_BASEADDR 0xE000D000
#define XPAR_XQSPIPS_0_HIGHADDR 0xE000DFFF
#define XPAR_XQSPIPS_0_QSPI_CLK_FREQ_HZ 200000000
#define XPAR_XQSPIPS_0_QSPI_MODE 0


/******************************************************************/


/***Definitions for Core_nIRQ/nFIQ interrupts ****/
/* Definitions for Fabric interrupts connected to ps7_scugic_0 */
#define XPAR_FABRIC_AXI_PERF_MON_1_INTERRUPT_INTR 91
#define XPAR_FABRIC_HDMI_OUTPUT_LOGICVC_1_INTERRUPT_INTR 90
#define XPAR_FABRIC_FMC_HDMI_INPUT_AXI_VDMA_1_S2MM_INTROUT_INTR 89
#define XPAR_FABRIC_PROCESSING_AXI_VDMA_2_S2MM_INTROUT_INTR 88
#define XPAR_FABRIC_PROCESSING_AXI_VDMA_2_MM2S_INTROUT_INTR 87
#define XPAR_FABRIC_PROCESSING_IMAGE_FILTER_1_INTERRUPT_INTR 86
#define XPAR_FABRIC_SYSTEM_HDMIO_INT_B_INTR 85

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to ps7_scugic_0 */

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_PS7_SCUGIC_0_DEVICE_ID 0
#define XPAR_PS7_SCUGIC_0_BASEADDR 0xF8F00100
#define XPAR_PS7_SCUGIC_0_HIGHADDR 0xF8F001FF
#define XPAR_PS7_SCUGIC_0_DIST_BASEADDR 0xF8F01000


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUGIC_0 */
#define XPAR_SCUGIC_0_DEVICE_ID 0
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF8F00100
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF8F001FF
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF8F01000


/******************************************************************/

/* Definitions for driver SCUTIMER */
#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_PS7_SCUTIMER_0_DEVICE_ID 0
#define XPAR_PS7_SCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_PS7_SCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUTIMER_0 */
#define XPAR_XSCUTIMER_0_DEVICE_ID XPAR_PS7_SCUTIMER_0_DEVICE_ID
#define XPAR_XSCUTIMER_0_BASEADDR 0xF8F00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xF8F0061F


/******************************************************************/

/* Definitions for driver SCUWDT */
#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_PS7_SCUWDT_0_DEVICE_ID 0
#define XPAR_PS7_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_PS7_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Canonical definitions for peripheral PS7_SCUWDT_0 */
#define XPAR_SCUWDT_0_DEVICE_ID XPAR_PS7_SCUWDT_0_DEVICE_ID
#define XPAR_SCUWDT_0_BASEADDR 0xF8F00620
#define XPAR_SCUWDT_0_HIGHADDR 0xF8F006FF


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_SD_0 */
#define XPAR_PS7_SD_0_DEVICE_ID 0
#define XPAR_PS7_SD_0_BASEADDR 0xE0100000
#define XPAR_PS7_SD_0_HIGHADDR 0xE0100FFF
#define XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ 50000000


/******************************************************************/

/* Canonical definitions for peripheral PS7_SD_0 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PS7_SD_0_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xE0100000
#define XPAR_XSDPS_0_HIGHADDR 0xE0100FFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 50000000


/******************************************************************/

/* Definitions for driver TPG */
#define XPAR_TPG_NUM_INSTANCES 1

/* Definitions for peripheral FMC_HDMI_INPUT_V_TPG_1 */
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_DEVICE_ID 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_BASEADDR 0x40080000
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_HIGHADDR 0x4008FFFF
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_S_AXIS_VIDEO_FORMAT 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_M_AXIS_VIDEO_FORMAT 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_S_AXI_CLK_FREQ_HZ 100000000
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_ACTIVE_ROWS 1080
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_ACTIVE_COLS 1920
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_PATTERN_CONTROL 4106
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_MOTION_SPEED 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_CROSS_HAIRS 6553700
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_ZPLATE_HOR_CONTROL 30
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_ZPLATE_VER_CONTROL 1
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_BOX_SIZE 50
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_BOX_COLOR 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_STUCK_PIXEL_THRESH 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_NOISE_GAIN 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_BAYER_PHASE 4
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_HAS_INTC_IF 0
#define XPAR_FMC_HDMI_INPUT_V_TPG_1_ENABLE_MOTION 0


/******************************************************************/

/* Canonical definitions for peripheral FMC_HDMI_INPUT_V_TPG_1 */
#define XPAR_TPG_0_DEVICE_ID XPAR_FMC_HDMI_INPUT_V_TPG_1_DEVICE_ID
#define XPAR_TPG_0_BASEADDR 0x40080000
#define XPAR_TPG_0_HIGHADDR 0x4008FFFF
#define XPAR_TPG_0_S_AXIS_VIDEO_FORMAT 0
#define XPAR_TPG_0_M_AXIS_VIDEO_FORMAT 0
#define XPAR_TPG_0_S_AXI_CLK_FREQ_HZ 100000000
#define XPAR_TPG_0_ACTIVE_ROWS 1080
#define XPAR_TPG_0_ACTIVE_COLS 1920
#define XPAR_TPG_0_PATTERN_CONTROL 4106
#define XPAR_TPG_0_MOTION_SPEED 0
#define XPAR_TPG_0_CROSS_HAIRS 6553700
#define XPAR_TPG_0_ZPLATE_HOR_CONTROL 30
#define XPAR_TPG_0_ZPLATE_VER_CONTROL 1
#define XPAR_TPG_0_BOX_SIZE 50
#define XPAR_TPG_0_BOX_COLOR 0
#define XPAR_TPG_0_STUCK_PIXEL_THRESH 0
#define XPAR_TPG_0_NOISE_GAIN 0
#define XPAR_TPG_0_BAYER_PHASE 4
#define XPAR_TPG_0_HAS_INTC_IF 0
#define XPAR_TPG_0_ENABLE_MOTION 0


/******************************************************************/

/* Definitions for driver UARTPS */
#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_UART_1 */
#define XPAR_PS7_UART_1_DEVICE_ID 0
#define XPAR_PS7_UART_1_BASEADDR 0xE0001000
#define XPAR_PS7_UART_1_HIGHADDR 0xE0001FFF
#define XPAR_PS7_UART_1_UART_CLK_FREQ_HZ 50000000
#define XPAR_PS7_UART_1_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PS7_UART_1 */
#define XPAR_XUARTPS_0_DEVICE_ID XPAR_PS7_UART_1_DEVICE_ID
#define XPAR_XUARTPS_0_BASEADDR 0xE0001000
#define XPAR_XUARTPS_0_HIGHADDR 0xE0001FFF
#define XPAR_XUARTPS_0_UART_CLK_FREQ_HZ 50000000
#define XPAR_XUARTPS_0_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPS */
#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_USB_0 */
#define XPAR_PS7_USB_0_DEVICE_ID 0
#define XPAR_PS7_USB_0_BASEADDR 0xE0002000
#define XPAR_PS7_USB_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Canonical definitions for peripheral PS7_USB_0 */
#define XPAR_XUSBPS_0_DEVICE_ID XPAR_PS7_USB_0_DEVICE_ID
#define XPAR_XUSBPS_0_BASEADDR 0xE0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xE0002FFF


/******************************************************************/

/* Definitions for driver VTC */
#define XPAR_XVTC_NUM_INSTANCES 1

/* Definitions for peripheral FMC_HDMI_INPUT_V_TC_1 */
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DEVICE_ID 0
#define XPAR_FMC_HDMI_INPUT_V_TC_1_BASEADDR 0x40070000
#define XPAR_FMC_HDMI_INPUT_V_TC_1_HIGHADDR 0x4007FFFF
#define XPAR_FMC_HDMI_INPUT_V_TC_1_GENERATE_EN 1
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DETECT_EN 1
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DET_HSYNC_EN 0
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DET_VSYNC_EN 0
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DET_HBLANK_EN 1
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DET_VBLANK_EN 1
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DET_AVIDEO_EN 1
#define XPAR_FMC_HDMI_INPUT_V_TC_1_DET_ACHROMA_EN 0


/******************************************************************/

/* Canonical definitions for peripheral FMC_HDMI_INPUT_V_TC_1 */
#define XPAR_VTC_0_DEVICE_ID XPAR_FMC_HDMI_INPUT_V_TC_1_DEVICE_ID
#define XPAR_VTC_0_BASEADDR 0x40070000
#define XPAR_VTC_0_HIGHADDR 0x4007FFFF
#define XPAR_VTC_0_GENERATE_EN 1
#define XPAR_VTC_0_DETECT_EN 1
#define XPAR_VTC_0_DET_HSYNC_EN 0
#define XPAR_VTC_0_DET_VSYNC_EN 0
#define XPAR_VTC_0_DET_HBLANK_EN 1
#define XPAR_VTC_0_DET_VBLANK_EN 1
#define XPAR_VTC_0_DET_AVIDEO_EN 1
#define XPAR_VTC_0_DET_ACHROMA_EN 0


/******************************************************************/

/* Definitions for driver XADCPS */
#define XPAR_XADCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS7_XADC_0 */
#define XPAR_PS7_XADC_0_DEVICE_ID 0
#define XPAR_PS7_XADC_0_BASEADDR 0xF8007100
#define XPAR_PS7_XADC_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Canonical definitions for peripheral PS7_XADC_0 */
#define XPAR_XADCPS_0_DEVICE_ID XPAR_PS7_XADC_0_DEVICE_ID
#define XPAR_XADCPS_0_BASEADDR 0xF8007100
#define XPAR_XADCPS_0_HIGHADDR 0xF8007120


/******************************************************************/

/* Xilinx FAT File System Library (XilFFs) User Settings */
#define FILE_SYSTEM_INTERFACE_SD
